"use client";
import { useEffect, useState, type FormEvent } from "react";
import { parseAdminKnowledgeIntake, parseAdminKnowledgeSeedBatchResponse, parseAdminKnowledgeSourceRemovalResponse, type AdminKnowledgeIntake } from "@xuyenviet/contracts";

function apiOrigin() { const origin = process.env.NEXT_PUBLIC_API_ORIGIN; if (!origin) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return origin; }
function signIn() { window.location.assign(`${apiOrigin()}/auth/google?${new URLSearchParams({ returnUrl: `${window.location.origin}/knowledge/intake` })}`); }
export function KnowledgeIntake() {
  const [intake, setIntake] = useState<AdminKnowledgeIntake | null>(null); const [urls, setUrls] = useState(""); const [label, setLabel] = useState(""); const [status, setStatus] = useState(""); const [busy, setBusy] = useState(false);
  async function request(path: string, method = "GET", body?: unknown) { const headers: Record<string, string> = { "x-request-id": crypto.randomUUID() }; if (method !== "GET") { const csrfResponse = await fetch(`${apiOrigin()}/auth/csrf`, { credentials: "include", headers, cache: "no-store" }); if (csrfResponse.status === 401) { signIn(); throw new Error("signin"); } const csrfBody: unknown = await csrfResponse.json().catch(() => null); const csrf = csrfBody && typeof csrfBody === "object" && typeof (csrfBody as { csrfToken?: unknown }).csrfToken === "string" ? (csrfBody as { csrfToken: string }).csrfToken : null; if (!csrfResponse.ok || !csrf) throw new Error("csrf unavailable"); headers["X-XuyenViet-CSRF"] = csrf; headers["content-type"] = "application/json"; } const response = await fetch(`${apiOrigin()}${path}`, { method, credentials: "include", headers, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const result: unknown = await response.json().catch(() => null); if (response.status === 401) { signIn(); throw new Error("signin"); } if (!response.ok) throw new Error("request failed"); return result; }
  async function load() { const parsed = parseAdminKnowledgeIntake(await request("/v1/admin/knowledge/intake")); if (!parsed) throw new Error("unsafe response"); setIntake(parsed); }
  useEffect(() => { void load().catch(() => setStatus("Không thể tải danh sách nguồn.")); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setStatus(""); try { const result = parseAdminKnowledgeSeedBatchResponse(await request("/v1/admin/knowledge/seed-batches", "POST", { urls: urls.split(/\r\n|\n|\r/).map((url) => url.trim()).filter(Boolean), ...(label.trim() ? { label: label.trim() } : {}) })); if (!result) throw new Error("unsafe response"); await load(); setUrls(""); setLabel(""); setStatus(`Đã nộp ${result.submittedCount} URL; ${result.failedCount} lỗi, ${result.duplicateCount} trùng.`); } catch { setStatus("Không thể nạp batch URL."); } finally { setBusy(false); } }
  async function remove(sourceId: string) { setBusy(true); setStatus(""); try { const result = parseAdminKnowledgeSourceRemovalResponse(await request(`/v1/admin/knowledge/sources/${encodeURIComponent(sourceId)}/removal`, "POST", { reason: "withdrawn" })); if (!result) throw new Error("unsafe response"); await load(); setStatus(result.status === "already_completed" ? "Nguồn này đã được gỡ trước đó." : "Đã gỡ nguồn và cập nhật tri thức liên quan."); } catch { setStatus("Không thể gỡ nguồn."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-6xl p-4 text-slate-900 sm:p-8"><header><p className="text-sm font-semibold text-emerald-800">KNOWLEDGE INTAKE</p><h1 className="mt-2 text-3xl font-bold">Nạp và gỡ nguồn tri thức</h1><p className="mt-3 text-slate-600">Chỉ hiển thị URL đã làm sạch và nguồn hiện hành an toàn. Trạng thái batch legacy không còn là read model của vận hành.</p></header><p className="mt-4" role="status">{status}</p><form className="mt-6 grid gap-3 rounded-xl border p-4" onSubmit={submit}><h2 className="font-semibold">Nạp batch URL</h2><input className="rounded border p-2" maxLength={160} onChange={(event) => setLabel(event.target.value)} placeholder="Nhãn batch (tùy chọn)" value={label} /><textarea className="min-h-40 rounded border p-2" onChange={(event) => setUrls(event.target.value)} placeholder="Mỗi URL một dòng" required value={urls} /><button className="w-fit rounded bg-emerald-800 px-4 py-2 text-white disabled:opacity-50" disabled={busy} type="submit">Nạp URL</button></form><section className="mt-6"><h2 className="text-xl font-bold">Nguồn đã nhập</h2><div className="mt-3 grid gap-3">{intake?.sources.map((source) => <article className="rounded-xl border p-4" key={source.id}><strong>{source.displayTitle}</strong><p className="break-all text-sm text-slate-600">{source.displayUrl ?? "URL không có sẵn"}</p><p className="mt-1 text-sm">{source.kind} · {source.eligibility === "eligible" ? "Đang hoạt động" : `Đã gỡ (${source.removalReason})`}</p>{source.eligibility === "eligible" ? <button className="mt-3 rounded border border-red-300 px-3 py-1 text-red-700" disabled={busy} onClick={() => void remove(source.id)} type="button">Gỡ nguồn</button> : null}</article>)}</div></section></main>;
}
