"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { parseAdminYoutubeCaptureDetail, type AdminYoutubeCaptureDetail } from "@xuyenviet/contracts";

function origin() { const value = process.env.NEXT_PUBLIC_API_ORIGIN; if (!value) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return value; }
function signIn() { window.location.assign(`${origin()}/auth/google?${new URLSearchParams({ returnUrl: `${window.location.origin}/knowledge/youtube-captures` })}`); }
export function YoutubeCaptureDetail({ sourceId }: { sourceId: string }) {
  const [detail, setDetail] = useState<AdminYoutubeCaptureDetail | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { const load = async () => { const response = await fetch(`${origin()}/v1/admin/knowledge/youtube-captures/${encodeURIComponent(sourceId)}`, { credentials: "include", headers: { "x-request-id": crypto.randomUUID() }, cache: "no-store" }); if (response.status === 401) { signIn(); return; } const parsed = parseAdminYoutubeCaptureDetail(await response.json().catch(() => null)); if (!response.ok || !parsed) throw new Error("unsafe response"); setDetail(parsed); }; void load().catch(() => setMessage("Không thể tải chi tiết bằng chứng YouTube.")); }, [sourceId]);
  return <main className="mx-auto max-w-4xl p-4 text-slate-900 sm:p-8"><Link className="text-emerald-800 underline" href="/knowledge/youtube-captures">Quay lại hàng đợi</Link><h1 className="mt-4 text-3xl font-bold">{detail?.sourceLabel ?? "Chi tiết bằng chứng YouTube"}</h1><p className="mt-3 text-slate-600">Chỉ hiển thị bằng chứng có cấu trúc và trạng thái kỹ thuật, không có nguồn thô hoặc dữ liệu thực thi AI.</p><p className="mt-3" role="status">{message}</p>{detail && <><section className="mt-6 rounded-xl border p-4"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="font-semibold">URL</dt><dd className="break-all">{detail.displayUrl ?? "Không có"}</dd></div><div><dt className="font-semibold">Xử lý kỹ thuật</dt><dd>{detail.ingestionJob?.status ?? "Chưa có tác vụ"}</dd></div><div><dt className="font-semibold">Thu thập</dt><dd>{detail.captureMethod} · {detail.capturedAt ?? "Chưa có"}</dd></div><div><dt className="font-semibold">Bằng chứng</dt><dd>{detail.evidenceCount} mục</dd></div></dl></section><section className="mt-6 grid gap-3">{detail.evidence.map((item, index) => <article className="rounded-xl border p-4" key={`${item.timestampStartSeconds}-${index}`}><p><strong>{item.category}</strong> · {item.evidenceType} · {item.confidence}</p><p className="mt-2">{item.claim}</p><p className="mt-2 text-sm text-slate-600">{item.timestampStartSeconds}s - {item.timestampEndSeconds}s · {item.excerpt}</p>{item.uncertaintyOrCondition && <p className="mt-2 text-sm">Điều kiện: {item.uncertaintyOrCondition}</p>}</article>)}</section></>}</main>;
}
