"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { parseAdminFacebookCaptureQueue, type AdminFacebookCaptureQueueStatus, type AdminFacebookCaptureQueue } from "@xuyenviet/contracts";
const statuses: AdminFacebookCaptureQueueStatus[] = ["in_progress", "needs_attention", "failed", "published", "suppressed"];
function origin() { const value = process.env.NEXT_PUBLIC_API_ORIGIN; if (!value) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return value; }
function signIn() { window.location.assign(`${origin()}/auth/google?${new URLSearchParams({ returnUrl: `${window.location.origin}/knowledge/facebook-captures` })}`); }
export function FacebookCaptureQueue() { const [queue, setQueue] = useState<AdminFacebookCaptureQueue | null>(null); const [status, setStatus] = useState<AdminFacebookCaptureQueueStatus>("in_progress"); const [page, setPage] = useState(1); const [message, setMessage] = useState(""); async function load(nextStatus = status, nextPage = page) { const response = await fetch(`${origin()}/v1/admin/knowledge/facebook-captures?${new URLSearchParams({ status: nextStatus, page: String(nextPage) })}`, { credentials: "include", headers: { "x-request-id": crypto.randomUUID() }, cache: "no-store" }); if (response.status === 401) { signIn(); return; } const parsed = parseAdminFacebookCaptureQueue(await response.json().catch(() => null)); if (!response.ok || !parsed) throw new Error("unsafe response"); setQueue(parsed); }
  useEffect(() => { void load().catch(() => setMessage("Không thể tải hàng đợi Facebook.")); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status, page]);
  return <main className="mx-auto max-w-6xl p-4 text-slate-900 sm:p-8"><p className="text-sm font-semibold text-emerald-800">FACEBOOK CAPTURES</p><h1 className="mt-2 text-3xl font-bold">Hàng đợi thu thập Facebook</h1><p className="mt-3 text-slate-600">Chỉ hiển thị trạng thái vận hành và metadata đã làm sạch.</p><p className="mt-3" role="status">{message}</p><div className="mt-6 flex flex-wrap gap-2">{statuses.map((item) => <button className={`rounded px-3 py-2 ${status === item ? "bg-emerald-800 text-white" : "border"}`} key={item} onClick={() => { setStatus(item); setPage(1); }} type="button">{item} ({queue?.counts[item] ?? 0})</button>)}</div><div className="mt-6 grid gap-3">{queue?.items.map((item) => <article className="rounded-xl border p-4" key={item.id}><div className="flex items-start justify-between gap-4"><div><strong>{item.sourceLabel}</strong><p className="mt-1 break-all text-sm text-slate-600">{item.displayUrl ?? "URL không có sẵn"}</p><p className="mt-1 text-sm">{item.ingestionJob ? `${item.ingestionJob.stage} · cập nhật ${new Date(item.ingestionJob.updatedAt).toLocaleString("vi-VN")}` : item.operationState === "recapture_pending" ? "Đang chờ thu thập lại" : "Đang chờ tạo tác vụ xử lý"}</p></div><Link className="rounded bg-emerald-800 px-3 py-2 text-white" href={`/knowledge/facebook-captures/${encodeURIComponent(item.id)}`}>Chi tiết</Link></div></article>)}</div>{queue && <div className="mt-6 flex gap-3"><button className="rounded border px-3 py-2 disabled:opacity-40" disabled={page === 1} onClick={() => setPage(page - 1)} type="button">Trang trước</button><span className="py-2">Trang {page}</span><button className="rounded border px-3 py-2 disabled:opacity-40" disabled={page * queue.pageSize >= queue.totalCount} onClick={() => setPage(page + 1)} type="button">Trang sau</button></div>}</main>; }
