"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { parseAdminFacebookCaptureCommandResult, parseAdminFacebookCaptureDetail, type AdminFacebookCaptureDetail } from "@xuyenviet/contracts";
function origin() { const value = process.env.NEXT_PUBLIC_API_ORIGIN; if (!value) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return value; }
function signIn(_id?: string) { window.location.assign(`${origin()}/auth/google?${new URLSearchParams({ returnUrl: `${window.location.origin}/knowledge/facebook-captures` })}`); }
export function FacebookCaptureDetail({ reviewId }: { reviewId: string }) { const [detail, setDetail] = useState<AdminFacebookCaptureDetail | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); async function request(path: string, method = "GET", body?: unknown) { const headers: Record<string, string> = { "x-request-id": crypto.randomUUID() }; if (method !== "GET") { const csrfResponse = await fetch(`${origin()}/auth/csrf`, { credentials: "include", headers, cache: "no-store" }); if (csrfResponse.status === 401) { signIn(reviewId); throw new Error("signin"); } const token = (await csrfResponse.json().catch(() => null) as { csrfToken?: unknown } | null)?.csrfToken; if (!csrfResponse.ok || typeof token !== "string") throw new Error("csrf unavailable"); headers["X-XuyenViet-CSRF"] = token; headers["content-type"] = "application/json"; } const response = await fetch(`${origin()}${path}`, { method, credentials: "include", headers, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); if (response.status === 401) { signIn(reviewId); throw new Error("signin"); } const value = await response.json().catch(() => null); if (!response.ok) throw new Error("request failed"); return value; }
  async function load() { const parsed = parseAdminFacebookCaptureDetail(await request(`/v1/admin/knowledge/facebook-captures/${encodeURIComponent(reviewId)}`)); if (!parsed) throw new Error("unsafe response"); setDetail(parsed); }
  useEffect(() => { void load().catch(() => setMessage("Không thể tải chi tiết an toàn.")); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reviewId]);
  async function command(kind: "recapture" | "rerun") { setBusy(true); setMessage(""); try { const result = parseAdminFacebookCaptureCommandResult(await request(`/v1/admin/knowledge/facebook-captures/${encodeURIComponent(reviewId)}/${kind === "rerun" ? "ingestion-rerun" : "recapture"}`, "POST", kind === "recapture" ? { reason: "Operator requested recapture" } : undefined)); if (!result) throw new Error("unsafe response"); setMessage(result.status === "updated" ? "Đã cập nhật tác vụ." : `Không thể thực hiện: ${result.status}.`); await load(); } catch { setMessage("Không thể cập nhật tác vụ."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-4xl p-4 text-slate-900 sm:p-8"><Link className="text-emerald-800 underline" href="/knowledge/facebook-captures">Quay lại hàng đợi</Link><h1 className="mt-4 text-3xl font-bold">{detail?.sourceLabel ?? "Chi tiết thu thập Facebook"}</h1><p className="mt-3 text-slate-600">Trang này không hiển thị văn bản nguồn, phản hồi AI thô, dữ liệu nhà cung cấp hoặc dữ liệu trình duyệt.</p><p className="mt-3" role="status">{message}</p>{detail && <><section className="mt-6 rounded-xl border p-4"><dl className="grid gap-3 sm:grid-cols-2"><div><dt className="font-semibold">URL</dt><dd className="break-all">{detail.displayUrl ?? "Không có"}</dd></div><div><dt className="font-semibold">Trạng thái</dt><dd>{detail.ingestionJob?.stage ?? detail.operationState}</dd></div><div><dt className="font-semibold">Thu thập</dt><dd>{detail.captureMethod ?? "Không có"} · {detail.capturedAt ?? "Chưa có"}</dd></div><div><dt className="font-semibold">Bài viết</dt><dd>{[detail.groupName, detail.authorText, detail.postCreatedAt].filter(Boolean).join(" · ") || "Không có metadata an toàn"}</dd></div></dl></section><section className="mt-6 flex gap-3">{detail.canRerunIngestion && <button className="rounded bg-emerald-800 px-4 py-2 text-white disabled:opacity-40" disabled={busy} onClick={() => void command("rerun")} type="button">Chạy lại xử lý</button>}{detail.canRecapture && <button className="rounded border px-4 py-2 disabled:opacity-40" disabled={busy} onClick={() => void command("recapture")} type="button">Thu thập lại</button>}</section></>}</main>; }
