import { eq } from "drizzle-orm";
import { beforeEach, describe, expect, test } from "vitest";
import { createPostgresAdminYoutubeCapturePort } from "@xuyenviet/database";

import { rawSourceMaterial, sourceCaptureVersions, sources, userRoles, users } from "@/db/schema";
import { serializeYoutubeEvidence, type YoutubeEvidence } from "@/features/knowledge/youtube-capture";
import { resetTestDatabase, testDb } from "./helpers/db";
import { seedSourceCaptureVersion } from "./helpers/source-captures";

const evidence: YoutubeEvidence[] = [{ category: "route", claim_vi: "Đèo Hải Vân cần kiểm tra thời tiết trước khi đi.", evidence_type: "spoken", timestamp_start_seconds: 60, timestamp_end_seconds: 85, confidence: "medium", freshness_sensitive: true, evidence_excerpt: "Hôm nay trên đèo có mưa.", uncertainty_or_condition: "Điều kiện thay đổi theo ngày." }];
async function createYoutubeCapture(input: { id: string; rawText?: string | null; captureMethod?: string }) { await testDb.insert(sources).values({ id: input.id, kind: "youtube", url: `https://www.youtube.com/watch?v=${input.id}`, canonicalUrl: `https://www.youtube.com/watch?v=${input.id}`, label: `Video ${input.id}`, sourceType: "community", verificationStatus: "unverified", official: false, partner: false, submittedByUserId: "operator-user" }); await testDb.insert(rawSourceMaterial).values({ id: `raw-${input.id}`, sourceId: input.id }); await seedSourceCaptureVersion({ sourceId: input.id, captureKind: "youtube", rawText: input.rawText ?? serializeYoutubeEvidence(evidence), rawMetadata: { kind: "youtube", captureMethod: input.captureMethod ?? "gemini_youtube_url", capturedAt: "2026-07-17T08:00:00.000Z", model: "gemini-test", promptVersion: "youtube-evidence-v1", providerPayload: "secret-provider-payload" } }); }
describe("admin YouTube capture adapter", () => {
  beforeEach(async () => { await resetTestDatabase(); await testDb.insert(users).values({ id: "operator-user", email: "operator@example.com" }); await testDb.insert(userRoles).values({ userId: "operator-user", role: "operator" }); });
  test("hydrates before pagination and projects bounded evidence without raw data", async () => { await createYoutubeCapture({ id: "valid" }); await createYoutubeCapture({ id: "invalid", rawText: "not-json" }); await createYoutubeCapture({ id: "wrong-method", captureMethod: "manual" }); const port = createPostgresAdminYoutubeCapturePort(); const queue = await port.list({ page: 1 }); const detail = await port.detail("valid"); expect(queue).toMatchObject({ totalCount: 1, items: [{ sourceId: "valid", evidenceCount: 1 }] }); expect(detail).toMatchObject({ sourceId: "valid", evidence: [{ claim: evidence[0].claim_vi, excerpt: evidence[0].evidence_excerpt }] }); expect(JSON.stringify({ queue, detail })).not.toMatch(/rawText|rawMetadata|provider-payload|secret-provider-payload/); });
  test("redacts URL credentials and sensitive metadata without exposing an invalid capture", async () => { await createYoutubeCapture({ id: "sensitive" }); await testDb.update(sources).set({ url: "https://user:password@youtube.com/watch?v=sensitive&token=private", canonicalUrl: "https://youtube.com/watch?v=sensitive&signature=private" }).where(eq(sources.id, "sensitive")); await testDb.update(sourceCaptureVersions).set({ rawMetadata: { kind: "youtube", captureMethod: "gemini_youtube_url", model: "provider payload private", promptVersion: "secret prompt" } }).where(eq(sourceCaptureVersions.sourceId, "sensitive")); const detail = await createPostgresAdminYoutubeCapturePort().detail("sensitive"); expect(detail).toMatchObject({ model: null, promptVersion: null, displayUrl: "https://youtube.com/watch?v=sensitive&signature=%5Bredacted%5D" }); expect(JSON.stringify(detail)).not.toMatch(/private|password/); expect(await createPostgresAdminYoutubeCapturePort().detail("missing")).toBeNull(); });
});
