CREATE TABLE "trip_recommendation_contexts" ("user_id" text NOT NULL, "conversation_id" text NOT NULL, "revision" integer NOT NULL, "fingerprint" text NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "trip_recommendation_contexts_user_id_conversation_id_pk" PRIMARY KEY("user_id","conversation_id"), CONSTRAINT "trip_recommendation_contexts_owner_fk" FOREIGN KEY ("conversation_id","user_id") REFERENCES "conversations"("id","user_id") ON DELETE cascade, CONSTRAINT "trip_recommendation_contexts_revision_check" CHECK ("revision" >= 1), CONSTRAINT "trip_recommendation_contexts_fingerprint_check" CHECK ("fingerprint" ~ '^[a-f0-9]{64}$'));
--> statement-breakpoint
CREATE TABLE "trip_recommendation_decisions" ("id" text PRIMARY KEY NOT NULL, "user_id" text NOT NULL, "conversation_id" text NOT NULL, "kind" text NOT NULL, "context_revision" integer NOT NULL, "context_fingerprint" text NOT NULL, "candidate_trip_project_id" text, "status" text DEFAULT 'open' NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "consumed_at" timestamp, CONSTRAINT "trip_recommendation_decisions_owner_fk" FOREIGN KEY ("conversation_id","user_id") REFERENCES "conversations"("id","user_id") ON DELETE cascade, CONSTRAINT "trip_recommendation_decisions_candidate_owner_fk" FOREIGN KEY ("candidate_trip_project_id","user_id") REFERENCES "trip_projects"("id","user_id") ON DELETE cascade, CONSTRAINT "trip_recommendation_decisions_kind_check" CHECK ("kind" in ('creation','context')), CONSTRAINT "trip_recommendation_decisions_revision_check" CHECK ("context_revision" >= 1), CONSTRAINT "trip_recommendation_decisions_fingerprint_check" CHECK ("context_fingerprint" ~ '^[a-f0-9]{64}$'), CONSTRAINT "trip_recommendation_decisions_status_check" CHECK ("status" in ('open','consumed','declined','private')));
--> statement-breakpoint
CREATE INDEX "trip_recommendation_decisions_owner_conversation_idx" ON "trip_recommendation_decisions" ("user_id","conversation_id","status");
--> statement-breakpoint
CREATE TABLE "trip_recommendation_declines" ("user_id" text NOT NULL, "conversation_id" text NOT NULL, "context_revision" integer NOT NULL, "fingerprint" text NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "trip_recommendation_declines_user_id_conversation_id_context_revision_pk" PRIMARY KEY("user_id","conversation_id","context_revision"), CONSTRAINT "trip_recommendation_declines_owner_fk" FOREIGN KEY ("conversation_id","user_id") REFERENCES "conversations"("id","user_id") ON DELETE cascade, CONSTRAINT "trip_recommendation_declines_revision_check" CHECK ("context_revision" >= 1), CONSTRAINT "trip_recommendation_declines_fingerprint_check" CHECK ("fingerprint" ~ '^[a-f0-9]{64}$'));
--> statement-breakpoint
CREATE TABLE "trip_recommendation_acceptances" ("user_id" text NOT NULL, "idempotency_key" text NOT NULL, "request_digest" text NOT NULL, "decision_id" text, "terminal_result" jsonb NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "trip_recommendation_acceptances_user_id_idempotency_key_pk" PRIMARY KEY("user_id","idempotency_key"), CONSTRAINT "trip_recommendation_acceptances_key_check" CHECK ("idempotency_key" ~ '^[A-Za-z0-9_-]{16,128}$'), CONSTRAINT "trip_recommendation_acceptances_digest_check" CHECK ("request_digest" ~ '^[a-f0-9]{64}$'));
