ALTER TABLE "source_capture_versions" ADD COLUMN "capture_method_version" text;--> statement-breakpoint
ALTER TABLE "source_capture_versions" ADD COLUMN "payload_schema_version" text;--> statement-breakpoint
UPDATE "source_capture_versions" SET "capture_method_version" = "raw_metadata"->>'captureMethodVersion', "payload_schema_version" = "raw_metadata"->>'payloadSchemaVersion' WHERE "capture_kind" = 'youtube' AND "capture_method_version" IS NULL AND "payload_schema_version" IS NULL AND "raw_metadata"->>'captureMethod' = 'gemini_youtube_url' AND "raw_metadata"->>'payloadSchemaVersion' = '2' AND "raw_metadata"->>'mediaResolution' IN ('MEDIA_RESOLUTION_LOW', 'MEDIA_RESOLUTION_MEDIUM', 'MEDIA_RESOLUTION_HIGH') AND "raw_metadata"->>'captureMethodVersion' = 'youtube-gemini-windowed-v4-aggregate-' || lower(replace("raw_metadata"->>'mediaResolution', 'MEDIA_RESOLUTION_', ''));--> statement-breakpoint
ALTER TABLE "source_capture_versions" ADD CONSTRAINT "source_capture_versions_compatibility_pair_check" CHECK ("capture_kind" <> 'youtube' OR (("capture_method_version" IS NULL AND "payload_schema_version" IS NULL) OR ("capture_method_version" IS NOT NULL AND "payload_schema_version" IS NOT NULL)));--> statement-breakpoint
CREATE TABLE "youtube_discovery_candidates" ("id" text PRIMARY KEY NOT NULL, "video_id" text NOT NULL, "canonical_url" text NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "youtube_discovery_candidates_video_id_check" CHECK ("video_id" ~ '^[A-Za-z0-9_-]{6,20}$'), CONSTRAINT "youtube_discovery_candidates_url_check" CHECK ("canonical_url" = 'https://www.youtube.com/watch?v=' || "video_id"));--> statement-breakpoint
CREATE UNIQUE INDEX "youtube_discovery_candidates_video_id_idx" ON "youtube_discovery_candidates" USING btree ("video_id");--> statement-breakpoint
CREATE TABLE "youtube_discovery_appearances" ("id" text PRIMARY KEY NOT NULL, "candidate_id" text NOT NULL REFERENCES "youtube_discovery_candidates"("id") ON DELETE restrict, "run_id" text NOT NULL REFERENCES "youtube_discovery_runs"("id") ON DELETE restrict, "result_ordinal" integer NOT NULL, "discovered_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "youtube_discovery_appearances_ordinal_check" CHECK ("result_ordinal" BETWEEN 0 AND 49));--> statement-breakpoint
CREATE UNIQUE INDEX "youtube_discovery_appearances_run_candidate_idx" ON "youtube_discovery_appearances" USING btree ("run_id","candidate_id");--> statement-breakpoint
CREATE UNIQUE INDEX "youtube_discovery_appearances_id_candidate_run_idx" ON "youtube_discovery_appearances" USING btree ("id","candidate_id","run_id");--> statement-breakpoint
CREATE INDEX "youtube_discovery_appearances_candidate_idx" ON "youtube_discovery_appearances" USING btree ("candidate_id");--> statement-breakpoint
CREATE UNIQUE INDEX "youtube_discovery_runs_id_policy_idx" ON "youtube_discovery_runs" USING btree ("id","policy_version_id");--> statement-breakpoint
CREATE TABLE "youtube_discovery_ranking_history" ("id" text PRIMARY KEY NOT NULL, "candidate_id" text NOT NULL REFERENCES "youtube_discovery_candidates"("id") ON DELETE restrict, "appearance_id" text, "run_id" text NOT NULL REFERENCES "youtube_discovery_runs"("id") ON DELETE restrict, "policy_version_id" text NOT NULL REFERENCES "youtube_discovery_policy_versions"("id") ON DELETE restrict, "stage" text NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, CONSTRAINT "youtube_discovery_ranking_history_appearance_provenance_fk" FOREIGN KEY ("appearance_id","candidate_id","run_id") REFERENCES "youtube_discovery_appearances"("id","candidate_id","run_id") ON DELETE restrict, CONSTRAINT "youtube_discovery_ranking_history_run_policy_fk" FOREIGN KEY ("run_id","policy_version_id") REFERENCES "youtube_discovery_runs"("id","policy_version_id") ON DELETE restrict, CONSTRAINT "youtube_discovery_ranking_history_stage_check" CHECK ("stage" IN ('discovered', 'enriched', 'triaged')), CONSTRAINT "youtube_discovery_ranking_history_discovered_appearance_check" CHECK ("stage" <> 'discovered' OR "appearance_id" IS NOT NULL));--> statement-breakpoint
CREATE INDEX "youtube_discovery_ranking_history_candidate_created_idx" ON "youtube_discovery_ranking_history" USING btree ("candidate_id","created_at");
