DROP INDEX "youtube_discovery_comment_signals_candidate_signal_idx";--> statement-breakpoint
CREATE UNIQUE INDEX "youtube_discovery_comment_signals_run_candidate_signal_idx" ON "youtube_discovery_comment_signals" USING btree ("run_id", "candidate_id", "signal");--> statement-breakpoint
ALTER TABLE "youtube_discovery_triages" ADD COLUMN "appearance_id" text;--> statement-breakpoint
UPDATE "youtube_discovery_triages" triage SET "appearance_id" = appearance.id FROM "youtube_discovery_appearances" appearance WHERE appearance.candidate_id = triage.candidate_id AND appearance.run_id = triage.run_id;--> statement-breakpoint
ALTER TABLE "youtube_discovery_triages" ALTER COLUMN "appearance_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "youtube_discovery_triages" ADD CONSTRAINT "youtube_discovery_triages_appearance_provenance_fk" FOREIGN KEY ("appearance_id", "candidate_id", "run_id") REFERENCES "youtube_discovery_appearances"("id", "candidate_id", "run_id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "youtube_discovery_triages" ADD CONSTRAINT "youtube_discovery_triages_run_policy_fk" FOREIGN KEY ("run_id", "policy_version_id") REFERENCES "youtube_discovery_runs"("id", "policy_version_id") ON DELETE restrict;--> statement-breakpoint
ALTER TABLE "youtube_discovery_triages" DROP CONSTRAINT "youtube_discovery_triages_signals_check";--> statement-breakpoint
ALTER TABLE "youtube_discovery_triages" ADD CONSTRAINT "youtube_discovery_triages_signals_check" CHECK ("signals" is null or ("signals" <@ array['recent_discussion','stale_or_changed_warning','practical_question_demand','creator_responsiveness','commercial_risk','contradictory_discussion']::text[] and cardinality("signals") between 0 and 6 and coalesce(cardinality(array_positions("signals", 'recent_discussion')), 0) <= 1 and coalesce(cardinality(array_positions("signals", 'stale_or_changed_warning')), 0) <= 1 and coalesce(cardinality(array_positions("signals", 'practical_question_demand')), 0) <= 1 and coalesce(cardinality(array_positions("signals", 'creator_responsiveness')), 0) <= 1 and coalesce(cardinality(array_positions("signals", 'commercial_risk')), 0) <= 1 and coalesce(cardinality(array_positions("signals", 'contradictory_discussion')), 0) <= 1));
