CREATE OR REPLACE FUNCTION youtube_discovery_text_array_unique(input_values text[]) RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$ SELECT cardinality(input_values) = (SELECT count(DISTINCT value) FROM unnest(input_values) AS value) $$;--> statement-breakpoint
UPDATE "youtube_discovery_recommendations" SET "factors" = ARRAY(SELECT value FROM (SELECT value, min(ordinality) AS first_ordinal FROM unnest("factors") WITH ORDINALITY AS item(value, ordinality) GROUP BY value) AS unique_values ORDER BY first_ordinal);--> statement-breakpoint
UPDATE "youtube_discovery_recommendations" SET "penalties" = ARRAY(SELECT value FROM (SELECT value, min(ordinality) AS first_ordinal FROM unnest("penalties") WITH ORDINALITY AS item(value, ordinality) GROUP BY value) AS unique_values ORDER BY first_ordinal);--> statement-breakpoint
UPDATE "youtube_discovery_recommendations" SET "signals" = ARRAY(SELECT value FROM (SELECT value, min(ordinality) AS first_ordinal FROM unnest("signals") WITH ORDINALITY AS item(value, ordinality) GROUP BY value) AS unique_values ORDER BY first_ordinal);--> statement-breakpoint
ALTER TABLE "youtube_discovery_recommendations" DROP CONSTRAINT "youtube_discovery_recommendations_codes_check";--> statement-breakpoint
ALTER TABLE "youtube_discovery_recommendations" ADD CONSTRAINT "youtube_discovery_recommendations_codes_check" CHECK ("recommendation" in ('skip','defer','consider') and "factors" <@ array['relevance','expected_value','freshness_fit']::text[] and youtube_discovery_text_array_unique("factors") and "penalties" <@ array['commercial_risk','duplicate_risk']::text[] and youtube_discovery_text_array_unique("penalties") and cardinality("factors") + cardinality("penalties") <= 5 and "reason" in ('eligible_score_band','below_defer_band','between_defer_and_consider_band','already_compatible','canonical_mismatch','not_current_run_enriched') and "signals" <@ array['recent_discussion','stale_or_changed_warning','practical_question_demand','creator_responsiveness','commercial_risk','contradictory_discussion']::text[] and youtube_discovery_text_array_unique("signals") and cardinality("signals") <= 6);--> statement-breakpoint
CREATE OR REPLACE FUNCTION youtube_discovery_recommendation_triage_update_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status <> 'succeeded' AND EXISTS (SELECT 1 FROM youtube_discovery_recommendations WHERE triage_id = OLD.id) THEN RAISE EXCEPTION 'youtube discovery recommendations require succeeded triage'; END IF; RETURN NEW; END; $$;--> statement-breakpoint
CREATE TRIGGER youtube_discovery_recommendation_triage_update_guard BEFORE UPDATE OF status ON "youtube_discovery_triages" FOR EACH ROW EXECUTE FUNCTION youtube_discovery_recommendation_triage_update_guard();--> statement-breakpoint
CREATE OR REPLACE FUNCTION youtube_discovery_recommendation_triage_delete_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS (SELECT 1 FROM youtube_discovery_recommendations WHERE triage_id = OLD.id) THEN RAISE EXCEPTION 'youtube discovery recommendations require succeeded triage'; END IF; RETURN OLD; END; $$;--> statement-breakpoint
CREATE TRIGGER youtube_discovery_recommendation_triage_delete_guard BEFORE DELETE ON "youtube_discovery_triages" FOR EACH ROW EXECUTE FUNCTION youtube_discovery_recommendation_triage_delete_guard();
