ALTER TABLE "youtube_discovery_policy_versions" ADD COLUMN IF NOT EXISTS "candidate_backlog_threshold" integer NOT NULL DEFAULT 100;
ALTER TABLE "youtube_discovery_policy_versions" DROP CONSTRAINT IF EXISTS "youtube_discovery_policy_versions_candidate_backlog_check";
ALTER TABLE "youtube_discovery_policy_versions" ADD CONSTRAINT "youtube_discovery_policy_versions_candidate_backlog_check" CHECK ("candidate_backlog_threshold" BETWEEN 1 AND 10000);
ALTER TABLE "youtube_discovery_appearances" ADD COLUMN IF NOT EXISTS "title" text, ADD COLUMN IF NOT EXISTS "description" text, ADD COLUMN IF NOT EXISTS "channel_id" text, ADD COLUMN IF NOT EXISTS "channel_name" text, ADD COLUMN IF NOT EXISTS "published_at" timestamp, ADD COLUMN IF NOT EXISTS "duration_seconds" integer, ADD COLUMN IF NOT EXISTS "category_id" text, ADD COLUMN IF NOT EXISTS "tags" text[], ADD COLUMN IF NOT EXISTS "view_count" integer, ADD COLUMN IF NOT EXISTS "like_count" integer, ADD COLUMN IF NOT EXISTS "comment_count" integer, ADD COLUMN IF NOT EXISTS "channel_subscriber_count" integer, ADD COLUMN IF NOT EXISTS "thumbnail_url" text;

CREATE TABLE IF NOT EXISTS "youtube_discovery_candidate_jobs" (
  "id" text PRIMARY KEY NOT NULL, "candidate_id" text NOT NULL REFERENCES "youtube_discovery_candidates"("id") ON DELETE RESTRICT, "appearance_id" text NOT NULL REFERENCES "youtube_discovery_appearances"("id") ON DELETE RESTRICT, "run_id" text NOT NULL REFERENCES "youtube_discovery_runs"("id") ON DELETE RESTRICT, "policy_version_id" text NOT NULL REFERENCES "youtube_discovery_policy_versions"("id") ON DELETE RESTRICT,
  "state" text NOT NULL DEFAULT 'queued', "next_run_at" timestamp NOT NULL DEFAULT now(), "claimed_by" text, "claimed_at" timestamp, "lease_expires_at" timestamp, "fencing_token" text, "attempt_count" integer NOT NULL DEFAULT 0, "max_retry_attempts" integer NOT NULL, "retry_delay_minutes" integer NOT NULL, "max_concurrent_jobs" integer NOT NULL,
  "terminal_at" timestamp, "terminal_outcome" text, "safe_error_code" text, "last_safe_stage" text, "created_at" timestamp NOT NULL DEFAULT now(),
  CONSTRAINT "youtube_discovery_candidate_jobs_state_check" CHECK (state IN ('queued','running','retrying','completed','failed','cancelled')),
  CONSTRAINT "youtube_discovery_candidate_jobs_snapshot_check" CHECK (attempt_count BETWEEN 0 AND max_retry_attempts + 1 AND max_retry_attempts BETWEEN 0 AND 10 AND retry_delay_minutes BETWEEN 1 AND 1440 AND max_concurrent_jobs BETWEEN 1 AND 20),
  CONSTRAINT "youtube_discovery_candidate_jobs_error_check" CHECK (safe_error_code IS NULL OR safe_error_code IN ('stage_transient','enrichment_transient','triage_transient','triage_timeout','eligibility_unavailable','recommendation_transient','persistence_contended','retry_exhausted','lease_retry_exhausted','policy_revoked')),
  CONSTRAINT "youtube_discovery_candidate_jobs_claim_check" CHECK ((claimed_by IS NULL AND claimed_at IS NULL AND lease_expires_at IS NULL AND fencing_token IS NULL) OR (claimed_by IS NOT NULL AND length(btrim(claimed_by)) BETWEEN 1 AND 160 AND claimed_at IS NOT NULL AND lease_expires_at > claimed_at AND fencing_token ~ '^[a-f0-9]{64}$')),
  CONSTRAINT "youtube_discovery_candidate_jobs_state_shape_check" CHECK ((state = 'queued' AND claimed_by IS NULL AND terminal_at IS NULL AND terminal_outcome IS NULL AND safe_error_code IS NULL AND last_safe_stage IS NULL) OR (state = 'running' AND claimed_by IS NOT NULL AND terminal_at IS NULL AND terminal_outcome IS NULL AND safe_error_code IS NULL AND last_safe_stage IS NULL) OR (state = 'retrying' AND claimed_by IS NULL AND next_run_at > created_at AND terminal_at IS NULL AND terminal_outcome IS NULL AND safe_error_code IN ('stage_transient','enrichment_transient','triage_transient','triage_timeout','eligibility_unavailable','recommendation_transient','persistence_contended') AND last_safe_stage IN ('enrichment','triage','eligibility','recommendation')) OR (state = 'completed' AND claimed_by IS NULL AND terminal_at IS NOT NULL AND terminal_outcome = 'completed' AND safe_error_code IS NULL) OR (state = 'failed' AND claimed_by IS NULL AND terminal_at IS NOT NULL AND terminal_outcome = 'failed' AND ((safe_error_code = 'lease_retry_exhausted' AND last_safe_stage IS NULL) OR (safe_error_code IN ('stage_transient','enrichment_transient','triage_transient','triage_timeout','eligibility_unavailable','recommendation_transient','persistence_contended','retry_exhausted') AND last_safe_stage IN ('enrichment','triage','eligibility','recommendation')))) OR (state = 'cancelled' AND claimed_by IS NULL AND terminal_at IS NOT NULL AND terminal_outcome = 'cancelled' AND safe_error_code = 'policy_revoked')),
  CONSTRAINT "youtube_discovery_candidate_jobs_appearance_provenance_fk" FOREIGN KEY ("appearance_id","candidate_id","run_id") REFERENCES "youtube_discovery_appearances"("id","candidate_id","run_id") ON DELETE RESTRICT,
  CONSTRAINT "youtube_discovery_candidate_jobs_run_policy_fk" FOREIGN KEY ("run_id","policy_version_id") REFERENCES "youtube_discovery_runs"("id","policy_version_id") ON DELETE RESTRICT
);
CREATE UNIQUE INDEX IF NOT EXISTS "youtube_discovery_candidate_jobs_appearance_idx" ON "youtube_discovery_candidate_jobs" ("appearance_id");
CREATE INDEX IF NOT EXISTS "youtube_discovery_candidate_jobs_claim_queue_idx" ON "youtube_discovery_candidate_jobs" ("state", "next_run_at", "created_at");
CREATE INDEX IF NOT EXISTS "youtube_discovery_candidate_jobs_lease_expiry_idx" ON "youtube_discovery_candidate_jobs" ("lease_expires_at") WHERE "lease_expires_at" IS NOT NULL;
ALTER TABLE "youtube_discovery_candidate_jobs" ADD COLUMN IF NOT EXISTS "incident_category" text;
ALTER TABLE "youtube_discovery_candidate_jobs" DROP CONSTRAINT IF EXISTS "youtube_discovery_candidate_jobs_incident_category_check";
ALTER TABLE "youtube_discovery_candidate_jobs" ADD CONSTRAINT "youtube_discovery_candidate_jobs_incident_category_check" CHECK ("incident_category" IS NULL OR "incident_category" IN ('provider_rate_limited','triage_schema_invalid','execution_terminal'));

INSERT INTO "youtube_discovery_candidate_jobs" ("id", "candidate_id", "appearance_id", "run_id", "policy_version_id", "state", "next_run_at", "max_retry_attempts", "retry_delay_minutes", "max_concurrent_jobs")
SELECT substring(md5('youtube-discovery-candidate-job:' || appearance.id) from 1 for 8) || '-' || substring(md5('youtube-discovery-candidate-job:' || appearance.id) from 9 for 4) || '-4' || substring(md5('youtube-discovery-candidate-job:' || appearance.id) from 14 for 3) || '-a' || substring(md5('youtube-discovery-candidate-job:' || appearance.id) from 18 for 3) || '-' || substring(md5('youtube-discovery-candidate-job:' || appearance.id) from 21 for 12), appearance.candidate_id, appearance.id, appearance.run_id, run.policy_version_id, 'queued', clock_timestamp(), run.max_retry_attempts, run.retry_delay_minutes, run.max_concurrent_runs
FROM "youtube_discovery_appearances" appearance JOIN "youtube_discovery_runs" run ON run.id = appearance.run_id
ON CONFLICT ("appearance_id") DO NOTHING;
