WITH current_policy AS (
  UPDATE "youtube_discovery_policy_versions"
  SET "is_current" = false
  WHERE "is_current" AND "query_builder_version" <> 2
  RETURNING *
), next_version AS (
  SELECT COALESCE(MAX("version"), 0) + 1 AS "version" FROM "youtube_discovery_policy_versions"
)
INSERT INTO "youtube_discovery_policy_versions" ("id", "version", "is_current", "enabled", "query_builder_version", "language_classifier_version", "minimum_useful_duration_seconds", "allow_foreign_fallback", "minimum_candidate_score", "priority_score_weight", "freshness_score_weight", "relevance_weight", "expected_value_weight", "freshness_fit_weight", "commercial_risk_weight", "duplicate_risk_weight", "defer_minimum", "consider_minimum", "cadence_minutes", "retention_days", "comment_signal_ttl_days", "max_concurrent_runs", "max_retry_attempts", "retry_delay_minutes", "candidate_backlog_threshold", "action_queue_high_priority_maximum", "action_queue_maximum_operator_review_age_hours", "action_queue_maximum_mission_stall_hours", "action_queue_persistent_incident_failure_count", "action_queue_persistent_incident_window_hours")
SELECT gen_random_uuid()::text, next_version."version", true, current_policy."enabled", 2, current_policy."language_classifier_version", current_policy."minimum_useful_duration_seconds", current_policy."allow_foreign_fallback", current_policy."minimum_candidate_score", current_policy."priority_score_weight", current_policy."freshness_score_weight", current_policy."relevance_weight", current_policy."expected_value_weight", current_policy."freshness_fit_weight", current_policy."commercial_risk_weight", current_policy."duplicate_risk_weight", current_policy."defer_minimum", current_policy."consider_minimum", current_policy."cadence_minutes", current_policy."retention_days", current_policy."comment_signal_ttl_days", current_policy."max_concurrent_runs", current_policy."max_retry_attempts", current_policy."retry_delay_minutes", current_policy."candidate_backlog_threshold", current_policy."action_queue_high_priority_maximum", current_policy."action_queue_maximum_operator_review_age_hours", current_policy."action_queue_maximum_mission_stall_hours", current_policy."action_queue_persistent_incident_failure_count", current_policy."action_queue_persistent_incident_window_hours"
FROM current_policy CROSS JOIN next_version;
