"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { parseAdminKnowledgeCard, parseAdminKnowledgeCardList, parseAdminKnowledgeRecommendationDetail, parseAdminKnowledgeRecommendationList, type AdminKnowledgeCard, type AdminKnowledgeRecommendationDetail, type AdminKnowledgeRecommendationList } from "@xuyenviet/contracts";

function origin() { const value = process.env.NEXT_PUBLIC_API_ORIGIN; if (!value) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return value; }
function signIn() { window.location.assign(`${origin()}/auth/google?${new URLSearchParams({ returnUrl: `${window.location.origin}/knowledge/cards` })}`); }
async function api(path: string) { const response = await fetch(`${origin()}${path}`, { credentials: "include", headers: { "x-request-id": crypto.randomUUID() } }); if (response.status === 401) { signIn(); throw new Error("signin"); } if (!response.ok) throw new Error("request"); return response.json() as Promise<unknown>; }
function cardState(card: Pick<AdminKnowledgeCard, "lifecycleState" | "knowledgeState" | "verificationRequirement">) { return `${card.lifecycleState} · ${card.knowledgeState} · ${card.verificationRequirement}`; }

export function KnowledgeCardList({ lifecycleState }: { lifecycleState: "draft" | "active" }) { const [items, setItems] = useState<AdminKnowledgeCard[]>([]); const [message, setMessage] = useState(""); useEffect(() => { void api(`/v1/admin/knowledge/cards?${new URLSearchParams({ lifecycleState })}`).then(parseAdminKnowledgeCardList).then((value) => { if (!value) throw new Error("unsafe"); setItems(value.items); }).catch(() => setMessage("Không thể tải thẻ tri thức.")); }, [lifecycleState]); const title = lifecycleState === "active" ? "Thẻ tri thức đang hoạt động" : "Thẻ đang chờ công việc vận hành"; return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold">{title}</h1><p className="mt-2 text-slate-600">Vòng đời thẻ, phân loại và yêu cầu xác minh luôn tách riêng với công việc vận hành.</p><p role="status">{message}</p><div className="mt-6 grid gap-3">{items.map((item) => <article className="rounded-xl border p-4" key={item.id}><h2 className="font-semibold">{item.title}</h2><p>{item.summary}</p><p className="mt-2 text-sm">{cardState(item)}{item.indexStatus ? ` · ${item.indexStatus.label}` : ""}</p><Link className="mt-3 inline-block text-emerald-800 underline" href={`/knowledge/cards/${encodeURIComponent(item.id)}`}>Xem thẻ</Link></article>)}</div></main>; }
export function KnowledgeCardDetail({ id }: { id: string }) { const [card, setCard] = useState<AdminKnowledgeCard | null>(null); const [message, setMessage] = useState(""); useEffect(() => { void api(`/v1/admin/knowledge/cards/${encodeURIComponent(id)}`).then(parseAdminKnowledgeCard).then((value) => { if (!value) throw new Error("unsafe"); setCard(value); }).catch(() => setMessage("Không thể tải thẻ tri thức.")); }, [id]); if (!card) return <main className="p-6" role="status">{message || "Đang tải..."}</main>; return <main className="mx-auto max-w-3xl p-6"><Link href="/knowledge/cards">Quay lại thẻ</Link><h1 className="mt-4 text-3xl font-bold">{card.title}</h1><p className="mt-2">{card.summary}</p><p className="mt-3 text-sm">{cardState(card)}{card.indexStatus ? ` · ${card.indexStatus.label}` : ""}</p><section className="mt-6"><h2 className="text-xl font-semibold">Chi tiết thực tế</h2>{Object.entries(card.practicalDetails).map(([key, item]) => <p className="mt-2" key={key}><strong>{key}:</strong> {Array.isArray(item) ? item.join(", ") : item}</p>)}</section></main>; }
export function RecommendationQueue({ id }: { id?: string }) { const [value, setValue] = useState<AdminKnowledgeRecommendationDetail | AdminKnowledgeRecommendationList | null>(null); const [message, setMessage] = useState(""); useEffect(() => { void (id ? api(`/v1/admin/knowledge/recommendations/${encodeURIComponent(id)}`).then(parseAdminKnowledgeRecommendationDetail) : api("/v1/admin/knowledge/recommendations").then(parseAdminKnowledgeRecommendationList)).then((parsed) => { if (!parsed) throw new Error("unsafe"); setValue(parsed); }).catch(() => setMessage("Không thể tải công việc vận hành.")); }, [id]); if (id && value && "card" in value && "evidence" in value) return <main className="mx-auto max-w-3xl p-6"><h1 className="text-3xl font-bold">{value.card.title}</h1><p>{value.card.summary}</p><p className="mt-3">Công việc: {value.workType} · {value.status} · {value.resolution ?? "chưa xử lý"}</p><p>Thẻ: {cardState(value.card)}</p><p className="mt-4 text-slate-600">Lấy mẫu là kiểm soát chất lượng, không phải điều kiện phê duyệt lại thẻ.</p><p role="status">{message}</p></main>; return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold">Công việc vận hành hiện hành</h1><p role="status">{message}</p>{value && "items" in value && <div className="mt-6 grid gap-3">{value.items.map((item) => <article className="rounded border p-4" key={item.id}><p><strong>{item.workType}</strong> · {item.status} · {item.resolution ?? "chưa xử lý"}</p><p>{item.card.title} · {cardState(item.card)}</p><Link href={`/knowledge/recommendations/${encodeURIComponent(item.id)}`}>Chi tiết</Link></article>)}</div>}</main>; }
