"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { parseAdminKnowledgeCard, parseAdminKnowledgeCardList, parseAdminKnowledgeRecommendationDetail, parseAdminKnowledgeRecommendationList, type AdminKnowledgeCard, type AdminKnowledgeRecommendationDetail, type AdminKnowledgeRecommendationList } from "@xuyenviet/contracts";

function origin() { const value = process.env.NEXT_PUBLIC_API_ORIGIN; if (!value) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return value; }
function signIn() { window.location.assign(`${origin()}/auth/google?${new URLSearchParams({ returnUrl: `${window.location.origin}/knowledge/cards` })}`); }
async function api(path: string, method = "GET", body?: unknown) { const headers: Record<string, string> = { "x-request-id": crypto.randomUUID() }; if (method !== "GET") { const csrfResponse = await fetch(`${origin()}/auth/csrf`, { credentials: "include", headers, cache: "no-store" }); if (csrfResponse.status === 401) { signIn(); throw new Error("signin"); } const csrfBody: unknown = await csrfResponse.json().catch(() => null); const csrf = csrfBody && typeof csrfBody === "object" && typeof (csrfBody as { csrfToken?: unknown }).csrfToken === "string" ? (csrfBody as { csrfToken: string }).csrfToken : null; if (!csrfResponse.ok || !csrf) throw new Error("csrf unavailable"); headers["X-XuyenViet-CSRF"] = csrf; headers["content-type"] = "application/json"; } const response = await fetch(`${origin()}${path}`, { method, credentials: "include", headers, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); if (response.status === 401) { signIn(); throw new Error("signin"); } if (!response.ok) throw new Error("request"); return response.json() as Promise<unknown>; }

const lifecycleLabels: Record<AdminKnowledgeCard["lifecycleState"], string> = { draft: "Bản nháp", pending_operator: "Chờ vận hành", active: "Đang hoạt động", suppressed: "Tạm ẩn", archived: "Đã lưu trữ", rejected: "Đã từ chối" };
const knowledgeStateLabels: Record<AdminKnowledgeCard["knowledgeState"], string> = { community_observation: "Quan sát cộng đồng", community_pattern: "Mẫu từ cộng đồng", conditional: "Có điều kiện", conflicted: "Có mâu thuẫn" };
const verificationLabels: Record<AdminKnowledgeCard["verificationRequirement"], string> = { none: "Không cần xác minh", operator_required: "Cần operator xác minh", failed: "Xác minh không đạt" };
const workTypeLabels = { risk: "Xử lý rủi ro", missing_context: "Bổ sung thông tin", verification: "Xác minh thông tin", relation: "Đối chiếu quan hệ", sampling: "Kiểm tra lấy mẫu" } as const;
const workStatusLabels = { open: "Chưa xử lý", resolved: "Đã xử lý", superseded: "Không còn hiệu lực" } as const;

function cardState(card: Pick<AdminKnowledgeCard, "lifecycleState" | "knowledgeState" | "verificationRequirement">) { return `${lifecycleLabels[card.lifecycleState]} · ${knowledgeStateLabels[card.knowledgeState]} · ${verificationLabels[card.verificationRequirement]}`; }

export function KnowledgeCardList() {
  const [items, setItems] = useState<AdminKnowledgeCard[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => { void api("/v1/admin/knowledge/cards?lifecycleState=active").then(parseAdminKnowledgeCardList).then((value) => { if (!value) throw new Error("unsafe"); setItems(value.items); }).catch(() => setMessage("Không thể tải thẻ tri thức.")); }, []);
  return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold">Thẻ tri thức đang hoạt động</h1><p className="mt-2 text-slate-600">Các yêu cầu cần operator xử lý được quản lý riêng tại Yêu cầu vận hành.</p><p role="status">{message}</p><div className="mt-6 grid gap-3">{items.map((item) => <article className="rounded-xl border p-4" key={item.id}><h2 className="font-semibold">{item.title}</h2><p>{item.summary}</p><p className="mt-2 text-sm">{cardState(item)}{item.indexStatus ? ` · ${item.indexStatus.label}` : ""}</p><Link className="mt-3 inline-block text-emerald-800 underline" href={`/knowledge/cards/${encodeURIComponent(item.id)}`}>Xem thẻ</Link></article>)}</div></main>;
}

export function KnowledgeCardDetail({ id }: { id: string }) {
  const [card, setCard] = useState<AdminKnowledgeCard | null>(null);
  const [message, setMessage] = useState("");
  useEffect(() => { void api(`/v1/admin/knowledge/cards/${encodeURIComponent(id)}`).then(parseAdminKnowledgeCard).then((value) => { if (!value) throw new Error("unsafe"); setCard(value); }).catch(() => setMessage("Không thể tải thẻ tri thức.")); }, [id]);
  if (!card) return <main className="p-6" role="status">{message || "Đang tải..."}</main>;
  const practicalDetails = Object.entries(card.practicalDetails);
  return <main className="mx-auto max-w-3xl p-6"><Link href="/knowledge/cards">Quay lại thẻ</Link><h1 className="mt-4 text-3xl font-bold">{card.title}</h1><p className="mt-2">{card.summary}</p><p className="mt-3 text-sm">{cardState(card)}{card.indexStatus ? ` · ${card.indexStatus.label}` : ""}</p>{card.conditions.length > 0 && <section className="mt-6"><h2 className="text-xl font-semibold">Điều kiện/Lưu ý</h2>{card.conditions.map((condition) => <p className="mt-2" key={condition}>{condition}</p>)}</section>}{practicalDetails.length > 0 && <section className="mt-6"><h2 className="text-xl font-semibold">Thông tin thực hành</h2>{practicalDetails.map(([key, item]) => <p className="mt-2" key={key}><strong>{key}:</strong> {Array.isArray(item) ? item.join(", ") : item}</p>)}</section>}</main>;
}

export function RecommendationQueue({ id }: { id?: string }) {
  const [value, setValue] = useState<AdminKnowledgeRecommendationDetail | AdminKnowledgeRecommendationList | null>(null);
  const [message, setMessage] = useState("");
  const [page, setPage] = useState(1);
  const [editSummary, setEditSummary] = useState("");
  async function load() { const parsed = id ? parseAdminKnowledgeRecommendationDetail(await api(`/v1/admin/knowledge/recommendations/${encodeURIComponent(id)}`)) : parseAdminKnowledgeRecommendationList(await api(`/v1/admin/knowledge/recommendations?${new URLSearchParams({ page: String(page) })}`)); if (!parsed) throw new Error("unsafe"); setValue(parsed); }
  useEffect(() => { void load().catch(() => setMessage("Không thể tải yêu cầu vận hành.")); }, [id, page]); // eslint-disable-line react-hooks/exhaustive-deps
  async function resolve(recommendationId: string, action: "accept_wording" | "edit" | "suppress" | "restore" | "verify" | "promote" | "resolve_relation" | "sampling_pass" | "sampling_fail") { try { const result = await api(`/v1/admin/knowledge/recommendations/${encodeURIComponent(recommendationId)}/resolve`, "POST", { action, ...(action === "edit" ? { editSummary } : {}) }); if (!result || typeof result !== "object") throw new Error("unsafe"); await load(); setMessage(action === "resolve_relation" ? "Đã xác nhận quan hệ và đưa thẻ vào hoạt động." : action === "suppress" ? "Đã tạm ẩn thẻ do mâu thuẫn." : action === "edit" ? "Đã mở lại yêu cầu để bổ sung thông tin." : "Đã gửi quyết định vận hành."); } catch { setMessage("Không thể gửi quyết định vận hành."); } }
  if (id && value && "evidence" in value) {
    const action = { risk: "suppress", missing_context: "edit", verification: "verify", relation: "resolve_relation" }[value.workType] as "edit" | "suppress" | "verify" | "resolve_relation" | undefined;
    const actionLabel = value.workType === "relation" ? "Xác nhận và đưa thẻ vào hoạt động" : value.workType === "verification" ? "Xác nhận đã xác minh" : value.workType === "risk" ? "Tạm ẩn thẻ" : "Xử lý yêu cầu";
    return <main className="mx-auto max-w-3xl p-6"><Link href="/knowledge/recommendations">Quay lại yêu cầu vận hành</Link><h1 className="mt-4 text-3xl font-bold">{value.card.title}</h1><dl className="mt-4 grid gap-3 rounded-xl border p-4"><div><dt className="font-semibold">Loại yêu cầu</dt><dd>{workTypeLabels[value.workType]}</dd></div><div><dt className="font-semibold">Trạng thái</dt><dd>{workStatusLabels[value.status]}</dd></div><div><dt className="font-semibold">Thẻ tri thức</dt><dd>{cardState(value.card)}</dd></div></dl>{value.status === "open" && value.workType === "relation" && <p className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-950">Kiểm tra các bằng chứng trước khi quyết định. Bạn có thể xác nhận thẻ, tạm ẩn thẻ, hoặc mở lại yêu cầu để bổ sung thông tin.</p>}{value.evidence.length > 0 && <section className="mt-6"><h2 className="text-xl font-semibold">Bằng chứng liên quan</h2>{value.evidence.map((item, index) => <article className="mt-3 rounded-xl border p-4" key={index}><p>{item.quote}</p>{item.conditions.length > 0 && <p className="mt-2 text-sm text-slate-600">Điều kiện: {item.conditions.join(", ")}</p>}</article>)}</section>}{value.status === "open" && value.workType === "relation" && <div className="mt-6 flex flex-wrap gap-3"><button className="rounded bg-emerald-700 px-3 py-2 text-white" onClick={() => void resolve(id, "resolve_relation")}>Xác nhận và đưa thẻ vào hoạt động</button><button className="rounded border border-amber-700 px-3 py-2 text-amber-900" onClick={() => void resolve(id, "suppress")}>Tạm ẩn do mâu thuẫn</button><button className="rounded border px-3 py-2" onClick={() => void resolve(id, "edit")}>Cần bổ sung thông tin</button></div>}{value.status === "open" && value.workType === "missing_context" && <div className="mt-6"><label className="block" htmlFor="edit-summary">Tóm tắt chỉnh sửa</label><textarea className="mt-2 w-full rounded border p-2" id="edit-summary" value={editSummary} onChange={(event) => setEditSummary(event.target.value)} /><button className="mt-2 rounded border px-3 py-2" disabled={!editSummary.trim()} onClick={() => void resolve(id, "edit")}>Gửi chỉnh sửa</button></div>}{value.status === "open" && action && value.workType !== "relation" && <button className="mt-6 rounded bg-emerald-700 px-3 py-2 text-white" onClick={() => void resolve(id, action)}>{actionLabel}</button>}{value.status === "open" && value.workType === "sampling" && <div className="mt-6 flex gap-3"><button className="rounded border px-3 py-2" onClick={() => void resolve(id, "sampling_pass")}>Đạt lấy mẫu</button><button className="rounded border px-3 py-2" onClick={() => void resolve(id, "sampling_fail")}>Không đạt lấy mẫu</button></div>}<p className="mt-4" role="status">{message}</p></main>;
  }
  if (!id && value && "items" in value) return <main className="mx-auto max-w-5xl p-6"><h1 className="text-3xl font-bold">Yêu cầu vận hành tri thức</h1><p className="mt-2 text-slate-600">Các thẻ tri thức cần xác minh, xử lý mâu thuẫn hoặc bổ sung thông tin.</p><p className="mt-3" role="status">{message}</p><div className="mt-6 grid gap-3">{value.items.map((item) => <article className="rounded-xl border p-5" key={item.id}><p className="font-semibold text-emerald-800">{workTypeLabels[item.workType]}</p><h2 className="mt-2 text-lg font-semibold">{item.card.title}</h2><p className="mt-1">{item.card.summary}</p><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-slate-600">Trạng thái</dt><dd>{workStatusLabels[item.status]}</dd></div><div><dt className="text-slate-600">Tình trạng thẻ</dt><dd>{cardState(item.card)}</dd></div></dl>{item.status === "open" && item.workType === "relation" && <div className="mt-4 flex flex-wrap gap-3"><button className="rounded bg-emerald-700 px-3 py-2 text-white" onClick={() => void resolve(item.id, "resolve_relation")}>Xác nhận</button><button className="rounded border border-amber-700 px-3 py-2 text-amber-900" onClick={() => void resolve(item.id, "suppress")}>Tạm ẩn</button><button className="rounded border px-3 py-2" onClick={() => void resolve(item.id, "edit")}>Cần bổ sung</button></div>}<Link className="mt-4 inline-block text-emerald-800 underline" href={`/knowledge/recommendations/${encodeURIComponent(item.id)}`}>Xem chi tiết và xử lý</Link></article>)}</div><div className="mt-6 flex gap-3"><button disabled={page === 1} onClick={() => setPage((current) => current - 1)} type="button">Trang trước</button><button disabled={value.items.length < 25} onClick={() => setPage((current) => current + 1)} type="button">Trang sau</button></div></main>;
  return <main className="p-6" role="status">{message || "Đang tải..."}</main>;
}
