"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { parseAdminYoutubeDiscoveryHealthIncidentDetail, type AdminYoutubeDiscoveryHealthIncidentDetail } from "@xuyenviet/contracts";

function origin() { const value = process.env.NEXT_PUBLIC_API_ORIGIN; if (!value) throw new Error("NEXT_PUBLIC_API_ORIGIN is required."); return value; }
function signIn() { window.location.assign(`${origin()}/auth/google?${new URLSearchParams({ returnUrl: window.location.href })}`); }

export function HealthIncidentDetail({ groupId }: { groupId: string }) {
  const [detail, setDetail] = useState<AdminYoutubeDiscoveryHealthIncidentDetail | null>(null); const [status, setStatus] = useState("Đang tải chi tiết sự cố."); const [failed, setFailed] = useState(false); const [loadingMore, setLoadingMore] = useState(false); const sequence = useRef(0); const active = useRef<AbortController | null>(null); const loadMoreButton = useRef<HTMLButtonElement | null>(null); const heading = useRef<HTMLHeadingElement>(null);
  async function load(cursor: string | null, append = false) { active.current?.abort(); const controller = new AbortController(); active.current = controller; const request = ++sequence.current; setFailed(false); if (append) setLoadingMore(true); else setStatus("Đang tải chi tiết sự cố."); try { const url = new URL(`${origin()}/v1/admin/knowledge/youtube-discovery/health/${encodeURIComponent(groupId)}`); if (cursor) url.searchParams.set("cursor", cursor); const response = await fetch(url, { credentials: "include", cache: "no-store", signal: controller.signal, headers: { "x-request-id": crypto.randomUUID() } }); if (response.status === 401) { signIn(); return; } const parsed = parseAdminYoutubeDiscoveryHealthIncidentDetail(await response.json().catch(() => null)); if (!response.ok || !parsed) throw new Error("unavailable"); if (request !== sequence.current) return; setDetail((current) => append && current ? { ...parsed, items: [...current.items, ...parsed.items.filter((item) => !new Set(current.items.map(({ runId }) => runId)).has(item.runId))] } : parsed); setStatus(append ? "Đã tải thêm các lần chạy của sự cố." : "Đã tải chi tiết sự cố an toàn."); if (!append) requestAnimationFrame(() => heading.current?.focus()); } catch { if (request === sequence.current && !controller.signal.aborted) { setFailed(true); setStatus("Không thể tải chi tiết sự cố lúc này."); } } finally { if (request === sequence.current) setLoadingMore(false); } }
  // The loader is intentionally recreated for current state setters; this effect only resets for a route change.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(null); return () => { sequence.current += 1; active.current?.abort(); }; }, [groupId]);
  useEffect(() => { if (!loadingMore) loadMoreButton.current?.focus(); }, [loadingMore]);
  return <main><Link className="inline-flex min-h-11 items-center border border-emerald-900 px-4 font-semibold" href="/knowledge/youtube-discovery/health">Quay lại sức khỏe</Link><h1 ref={heading} tabIndex={-1} className="mt-5 text-3xl font-bold outline-none">Chi tiết sự cố Discovery</h1><p role="status" aria-live="polite" className="mt-3">{status}</p>{failed ? <button className="mt-4 min-h-11 border border-emerald-900 px-4 font-semibold" onClick={() => void load(null)} type="button">Thử lại</button> : detail ? <><ul className="mt-4 grid gap-3">{detail.items.map(({ stage: runStage, phase, ...item }) => <li className="border p-4" key={item.runId}><strong>Pha vòng đời: {phaseLabel(phase)}</strong><dl className="mt-2 grid gap-1 text-sm"><div><dt className="inline font-semibold">Giai đoạn: </dt><dd className="inline">{stageLabel(runStage)}</dd></div><div><dt className="inline font-semibold">Mã lần chạy: </dt><dd className="inline">{item.runId}</dd></div><div><dt className="inline font-semibold">Trạng thái: </dt><dd className="inline">{stateLabel(item.state)}</dd></div><div><dt className="inline font-semibold">Thời điểm: </dt><dd className="inline">{format(item.at)}</dd></div>{item.nextRunAt ? <div><dt className="inline font-semibold">Thử lại lúc: </dt><dd className="inline">{format(item.nextRunAt)}</dd></div> : null}<div><dt className="inline font-semibold">Số lần thử lại: </dt><dd className="inline">{item.retryCount}</dd></div><div><dt className="inline font-semibold">Danh mục: </dt><dd className="inline">{categoryLabel(item.category)}</dd></div></dl></li>)}</ul>{detail.nextCursor ? <button ref={loadMoreButton} className="mt-4 min-h-11 border border-emerald-900 px-4 font-semibold" disabled={loadingMore} onClick={() => void load(detail.nextCursor, true)} type="button">{loadingMore ? "Đang tải thêm" : "Tải thêm"}</button> : null}</> : null}</main>;
}

function format(value: string) { return new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function stageLabel(value: AdminYoutubeDiscoveryHealthIncidentDetail["items"][number]["stage"]) { return value === "unavailable" ? "Không khả dụng" : value; }
function phaseLabel(value: AdminYoutubeDiscoveryHealthIncidentDetail["items"][number]["phase"]) { return value === "retrying" ? "Đang thử lại" : value === "terminal" ? "Đã kết thúc" : "Đã hoàn tất"; }
function stateLabel(value: AdminYoutubeDiscoveryHealthIncidentDetail["items"][number]["state"]) { return value === "retrying" ? "Đang thử lại" : value === "failed" ? "Đã thất bại" : "Đã hoàn tất"; }
function categoryLabel(value: AdminYoutubeDiscoveryHealthIncidentDetail["category"]) { return value === "provider_rate_limited" ? "Giới hạn tốc độ nhà cung cấp" : value === "triage_schema_invalid" ? "Dữ liệu phân loại không hợp lệ" : "Lỗi thực thi đã kết thúc"; }
