import Link from "next/link";

const routine = [
  { title: "Bắt đầu từ tổng quan", body: "Kiểm tra số bản nháp cần duyệt, khuyến nghị đang mở, thẻ cần xác minh và lỗi pipeline. Ưu tiên việc đang chặn chất lượng trước khi tăng số lượng.", href: "/", action: "Mở tổng quan" },
  { title: "Xử lý hàng đợi cần quyết định", body: "Duyệt bản nháp sau khi kiểm tra claim và bằng chứng. Với khuyến nghị còn hiệu lực, mở chi tiết để đối chiếu trước khi chọn xuất bản, cảnh báo hoặc không xuất bản.", href: "/knowledge/recommendations", action: "Mở khuyến nghị" },
  { title: "Theo dõi tác vụ thất bại", body: "Mở hàng đợi Facebook ở nhóm xử lý thất bại để đọc chi tiết. Không mặc định rằng mọi lỗi đều có thể chạy lại từ UI; chỉ dùng thao tác hiện diện trên màn hình.", href: "/knowledge/facebook-captures?status=failed", action: "Mở lỗi pipeline" },
  { title: "Kiểm tra tri thức đã xuất bản", body: "Nếu cần AI dùng một thẻ, xem trạng thái chỉ mục và điều kiện bằng chứng. Thẻ đã phê duyệt nhưng chưa index hoặc chưa đủ evidence chưa sẵn sàng để kỳ vọng AI truy xuất.", href: "/knowledge/approved", action: "Mở tri thức đã phê duyệt" },
  { title: "Dùng coverage để chọn việc tiếp theo", body: "Xem các khoảng trống, thẻ cần kiểm tra/xác minh và công việc hiện hành. Nạp nguồn mới chỉ khi nó giúp giải quyết một khoảng trống hoặc khuyến nghị có cơ sở.", href: "/knowledge/progress", action: "Mở coverage" },
];

export default function OperatingRoutineGuidePage() {
  return <div><header><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#8c4f13]">Hướng dẫn 03</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Quy trình vận hành hằng ngày</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#4f625a]">Mục tiêu không phải là xử lý nhanh mọi hàng đợi, mà là giữ tri thức dùng cho du khách có bằng chứng và trạng thái phù hợp.</p></header><ol className="mt-8 grid gap-4">{routine.map((item, index) => <li className="grid gap-4 rounded-[1.5rem] border border-[#d8c9ad] bg-white/75 p-5 sm:grid-cols-[3rem_1fr_auto] sm:items-start" key={item.title}><span className="flex size-10 items-center justify-center rounded-full bg-[#1f5f46] text-sm font-semibold text-white">{index + 1}</span><div><h2 className="text-2xl font-semibold tracking-[-0.03em] text-[#17342c]">{item.title}</h2><p className="mt-3 leading-7 text-[#4f625a]">{item.body}</p></div><Link className="min-h-11 rounded-xl border border-[#8fb59f] px-4 py-3 text-center font-semibold text-[#1f5f46] transition hover:bg-[#edf7ef] focus:outline-none focus:ring-4 focus:ring-[#8fb59f]" href={item.href}>{item.action}</Link></li>)}</ol><section className="mt-8 rounded-[1.5rem] border border-[#d99a93] bg-[#fff0ee] p-5 sm:p-6"><h2 className="text-2xl font-semibold tracking-[-0.03em] text-[#9b2f29]">Khi không có thao tác phù hợp</h2><p className="mt-3 leading-7 text-[#4f625a]">Ghi nhận trạng thái, bằng chứng cần đối chiếu và màn hình liên quan để chuyển cho người phụ trách kỹ thuật hoặc chính sách. Không tự sửa dữ liệu, bỏ qua xác minh, hoặc coi trạng thái đã bị giữ lại là có thể xuất bản.</p></section></div>;
}
