import Link from "next/link";

const routine = [
  { title: "Bắt đầu từ tổng quan và mức độ bao phủ", body: "Kiểm tra khoảng trống, yêu cầu đang mở, thẻ cần xác minh và tác vụ lỗi. Ưu tiên việc đang chặn độ an toàn hoặc mức độ bao phủ trước khi tăng số URL.", href: "/", action: "Mở tổng quan" },
  { title: "Chọn nguồn để bổ sung", body: "Dùng mức độ bao phủ hoặc yêu cầu hiện hành để xác định khoảng trống, sau đó nạp URL. Trang Nạp nguồn cho biết loại nguồn và đã có nội dung thu thập hay chưa, không phải trạng thái xuất bản.", href: "/knowledge/intake", action: "Mở nạp nguồn" },
  { title: "Theo dõi thu thập và xử lý", body: "Vào Facebook hoặc YouTube để xem lần thu thập, bằng chứng và tác vụ kỹ thuật. Một tác vụ hoàn thành có thể chứa kết quả ứng viên khác nhau; chỉ chạy lại hoặc thu thập lại khi màn hình cho phép.", href: "/knowledge/facebook-captures", action: "Mở Facebook" },
  { title: "Xử lý yêu cầu còn hiệu lực", body: "Với yêu cầu đang mở, đối chiếu bằng chứng rồi chọn quyết định được màn hình cho phép. Quyết định AI, vòng đời thẻ và kết quả xử lý yêu cầu là ba lớp riêng; không xử lý mục không còn hiệu lực.", href: "/knowledge/recommendations", action: "Mở yêu cầu" },
  { title: "Kiểm tra điều kiện dùng cho câu trả lời", body: "Muốn AI dùng một thẻ, xác nhận thẻ đang hoạt động, không cần xác minh thêm và bằng chứng/nguồn còn hợp lệ. Trạng thái chỉ mục chỉ phản ánh bước tìm kiếm; hệ thống vẫn tự chặn thẻ không đủ điều kiện.", href: "/knowledge/cards", action: "Mở thẻ tri thức" },
  { title: "Chuyển tuyến lỗi hoặc thiếu thao tác", body: "Ghi nhận nguồn, lần thu thập/tác vụ, thẻ hoặc yêu cầu liên quan, trạng thái hiển thị và thời điểm. Không tự sửa dữ liệu, không nhập lại URL để né lỗi và không coi trạng thái kỹ thuật là quyết định xuất bản.", href: "/guides/data-states", action: "Xem trạng thái" },
];

export default function OperatingRoutineGuidePage() {
  return <div><header><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#8c4f13]">Hướng dẫn 03</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Quy trình vận hành hằng ngày</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#4f625a]">Mục tiêu không phải là xử lý nhanh mọi hàng đợi, mà là giữ tri thức dùng cho du khách có bằng chứng, vòng đời và điều kiện sử dụng phù hợp.</p></header><ol className="mt-8 grid gap-4">{routine.map((item, index) => <li className="grid gap-4 rounded-[1.5rem] border border-[#d8c9ad] bg-white/75 p-5 sm:grid-cols-[3rem_1fr_auto] sm:items-start" key={item.title}><span className="flex size-10 items-center justify-center rounded-full bg-[#1f5f46] text-sm font-semibold text-white">{index + 1}</span><div><h2 className="text-2xl font-semibold tracking-[-0.03em] text-[#17342c]">{item.title}</h2><p className="mt-3 leading-7 text-[#4f625a]">{item.body}</p></div><Link className="min-h-11 rounded-xl border border-[#8fb59f] px-4 py-3 text-center font-semibold text-[#1f5f46] transition hover:bg-[#edf7ef] focus:outline-none focus:ring-4 focus:ring-[#8fb59f]" href={item.href}>{item.action}</Link></li>)}</ol><section className="mt-8 rounded-[1.5rem] border border-[#d99a93] bg-[#fff0ee] p-5 sm:p-6"><h2 className="text-2xl font-semibold tracking-[-0.03em] text-[#9b2f29]">Khi không có thao tác phù hợp</h2><p className="mt-3 leading-7 text-[#4f625a]">Ghi nhận nguồn, lần thu thập/tác vụ, thẻ hoặc yêu cầu liên quan cùng trạng thái và thời điểm để chuyển cho người phụ trách kỹ thuật hoặc chính sách. Không tự sửa dữ liệu, bỏ qua quy trình an toàn, hoặc coi trạng thái kỹ thuật là quyền xuất bản.</p></section></div>;
}
