import { Controller, Get } from "@nestjs/common";

import { PublicRoute } from "./auth/public-route.decorator";

@Controller()
export class OpenApiController {
  @Get("openapi.json")
  @PublicRoute()
  document() {
    const directApiSecurity = [{ bearerAuth: [] }, { browserSession: [] }];
    return {
      openapi: "3.0.3",
      info: { title: "XuyenViet Private API", version: "v1" },
      paths: {
        "/health/live": { get: { summary: "Process liveness only; does not query dependencies.", responses: { "200": jsonResponse("Process is running", "Health") } } },
        "/health/ready": { get: { summary: "Configuration, issuer-key, database, and compatible-schema admission readiness.", responses: { "200": jsonResponse("Ready for assigned traffic", "Health"), "503": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/version": { get: { summary: "API version and bounded conversation-summary list limit.", responses: { "200": jsonResponse("Version metadata", "ApiVersion") } } },
        "/v1/conversations/summaries": { get: { summary: "Owner-scoped ordinary conversation summaries. The retained BFF bearer path or a direct Nest browser session supplies the owner principal; trip-project conversations are excluded. Results are bounded, unpaginated, and ordered by updatedAt DESC then id DESC.", security: directApiSecurity, responses: { "200": jsonResponse("Owner summaries", "ConversationSummaryList"), "401": { $ref: "#/components/responses/SafeError" }, "500": { $ref: "#/components/responses/SafeError" }, "503": { $ref: "#/components/responses/SafeError" } } } },
        "/auth/google": { get: { summary: "Starts Nest-owned Google OAuth with a configured allowlisted return URL and PKCE. The redirect sets a host-only secure HttpOnly SameSite=Lax transaction cookie containing only an opaque transaction ID; it never serializes provider tokens, state, verifier, session values, or CSRF material.", parameters: [{ name: "returnUrl", in: "query", required: true, schema: { type: "string", format: "uri" } }], responses: { "302": { description: "Google authorization redirect" }, "401": { $ref: "#/components/responses/SafeError" }, "503": { $ref: "#/components/responses/SafeError" } } } },
        "/auth/google/callback": { get: { summary: "Requires the host-only OAuth transaction cookie to match the state transaction ID before one-time consumption, clears it on every callback outcome, creates an opaque secure HttpOnly browser session on success, and redirects only to the configured application origin.", responses: { "302": { description: "Configured application redirect" }, "401": { $ref: "#/components/responses/SafeError" }, "503": { $ref: "#/components/responses/SafeError" } } } },
        "/auth/csrf": { get: { summary: "Returns the session-bound CSRF nonce only to an admitted Nest browser session from its exact configured origin. The nonce is not an authentication credential and this response never includes a session value or ID, OAuth/provider token, BFF credential, or signing material.", security: [{ browserSession: [] }], responses: { "200": jsonResponse("Session-bound CSRF nonce", "BrowserCsrfNonce"), "401": { $ref: "#/components/responses/SafeError" } } } },
        "/auth/logout": { post: { summary: "Revokes the admitted Nest browser session and clears its secure HttpOnly cookie. Browser mutation admission requires an exact configured Origin and session-bound CSRF proof.", security: [{ browserSession: [] }], parameters: [csrfHeaderParameter()], responses: { "204": { description: "Session revoked" }, "401": { $ref: "#/components/responses/SafeError" }, "403": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/conversations/planning-context/{tripProjectId}": { get: { summary: "Owner-scoped current TripAnswerContext v1 for the selected project. The retained BFF bearer path or a direct Nest browser session supplies the owner principal. Missing and foreign projects return context null. This bounded response has deterministic canonical ordering and no pagination.", security: directApiSecurity, parameters: [{ name: "tripProjectId", in: "path", required: true, schema: { type: "string", maxLength: 128 } }], responses: { "200": jsonResponse("Current planning context", "PlanningContext"), "401": { $ref: "#/components/responses/SafeError" }, "500": { $ref: "#/components/responses/SafeError" }, "503": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/conversations/{conversationId}/answers/{assistantMessageId}": { get: { summary: "Owner-scoped historic completed assistant detail. The retained BFF bearer path or a direct Nest browser session supplies the owner principal. Missing and foreign resources return detail null. Provenance is formatter-derived and bounded by 100 rank-ascending entries; unavailable entries disclose only their marker.", security: directApiSecurity, parameters: [{ name: "conversationId", in: "path", required: true, schema: { type: "string", maxLength: 128 } }, { name: "assistantMessageId", in: "path", required: true, schema: { type: "string", maxLength: 128 } }], responses: { "200": jsonResponse("Historic answer detail", "PlanningAnswerDetail"), "401": { $ref: "#/components/responses/SafeError" }, "500": { $ref: "#/components/responses/SafeError" }, "503": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/ai-ask/stream": { post: { summary: "Streams AI responses for the retained BFF bearer path or a direct Nest browser session. Direct browser use requires exact configured Origin and session-bound X-XuyenViet-CSRF proof.", security: directApiSecurity, parameters: [csrfHeaderParameter()], responses: { "201": { description: "NDJSON answer stream" }, "400": { $ref: "#/components/responses/SafeError" }, "401": { $ref: "#/components/responses/SafeError" }, "403": { $ref: "#/components/responses/SafeError" }, "503": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/admin/workspace": { get: { summary: "Admin workspace bootstrap. Private admin BFF bearer credentials only.", security: [{ bearerAuth: [] }], responses: { "200": { description: "Admin workspace ready" }, "401": { $ref: "#/components/responses/SafeError" }, "403": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/admin/users": { get: { summary: "Exact-admin user roster. Private bearer credentials only; pages are cursor-ordered by name, email, id and project safe usage aggregates.", security: [{ bearerAuth: [] }], parameters: [{ name: "cursor", in: "query", schema: { type: "string", maxLength: 512 } }, { name: "search", in: "query", schema: { type: "string", maxLength: 120 } }], responses: { "200": jsonResponse("Admin user roster", "AdminUserRosterPage"), "400": { $ref: "#/components/responses/SafeError" }, "401": { $ref: "#/components/responses/SafeError" }, "403": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/admin/users/{userId}/roles": { post: { summary: "Grant operator or admin role. Exact-admin only; the command atomically audits and invalidates changed target credentials.", security: [{ bearerAuth: [] }], parameters: [{ name: "userId", in: "path", required: true, schema: { type: "string", maxLength: 128 } }], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UserRoleBody" } } } }, responses: { "200": jsonResponse("Role command result", "UserRoleCommandResult"), "400": { $ref: "#/components/responses/SafeError" }, "401": { $ref: "#/components/responses/SafeError" }, "403": { $ref: "#/components/responses/SafeError" } } } },
        "/v1/admin/users/{userId}/roles/{role}": { delete: { summary: "Revoke operator or admin role. Exact-admin only; the final active admin cannot be revoked.", security: [{ bearerAuth: [] }], parameters: [{ name: "userId", in: "path", required: true, schema: { type: "string", maxLength: 128 } }, { name: "role", in: "path", required: true, schema: { type: "string", enum: ["operator", "admin"] } }], responses: { "200": jsonResponse("Role command result", "UserRoleCommandResult"), "400": { $ref: "#/components/responses/SafeError" }, "401": { $ref: "#/components/responses/SafeError" }, "403": { $ref: "#/components/responses/SafeError" } } } },
      },
      components: {
        securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "ES256 JWT", description: "Private BFF credential path retained during the direct-browser cutover; it is not retired by this API contract." }, browserSession: { type: "apiKey", in: "cookie", name: "__Host-xuyenviet-session", description: "Nest-managed opaque secure HttpOnly browser session accepted by applicable direct API routes. Unsafe requests require exact configured Origin plus session-bound X-XuyenViet-CSRF proof; credentialed CORS is configured by explicit origin only." } },
        schemas: {
          Health: { type: "object", required: ["status"], properties: { status: { type: "string", enum: ["ok"] } } },
           ApiVersion: { type: "object", required: ["version", "conversationSummaryLimit"], properties: { version: { type: "string", enum: ["v1"] }, conversationSummaryLimit: { type: "integer", minimum: 1, maximum: 100 } } },
           BrowserCsrfNonce: { type: "object", required: ["csrfToken"], properties: { csrfToken: { type: "string", pattern: "^[A-Za-z0-9_-]{43}$", description: "Session-bound CSRF nonce. It is not an authentication credential." } }, additionalProperties: false },
           ConversationSummary: { type: "object", required: ["id", "updatedAt", "preview"], properties: { id: { type: "string", minLength: 1, maxLength: 128 }, updatedAt: { type: "string", format: "date-time", pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$", description: "Canonical ISO-8601 UTC timestamp." }, preview: { type: "string", maxLength: 61 } } },
           ConversationSummaryList: { type: "object", required: ["summaries"], properties: { summaries: { type: "array", maxItems: 100, items: { $ref: "#/components/schemas/ConversationSummary" } } } },
              PlanningContext: { type: "object", required: ["context"], properties: { context: nullableReference("TripAnswerContext", "Missing and foreign ownership are both null.") } },
            TripAnswerContext: { type: "object", required: ["version", "hasProjectScope", "tripProjectId", "aggregateVersion", "primaryConversationId", "anchors", "planItems", "constraints", "currentConversationFacts", "conflicts"], properties: { version: { type: "integer", enum: [1] }, hasProjectScope: { type: "boolean" }, tripProjectId: { type: "string", nullable: true, maxLength: 128 }, aggregateVersion: { type: "integer", nullable: true, minimum: 0 }, primaryConversationId: { type: "string", nullable: true, maxLength: 128 }, anchors: { type: "array", maxItems: 60, description: "Canonical deterministic order.", items: { $ref: "#/components/schemas/ContextFact" } }, planItems: { type: "array", maxItems: 60, description: "Canonical deterministic plan order.", items: { $ref: "#/components/schemas/PlanItem" } }, constraints: { oneOf: [{ type: "object", nullable: true, enum: [null] }, { $ref: "#/components/schemas/ContextConstraints" }] }, currentConversationFacts: { type: "array", maxItems: 18, description: "Canonical deterministic order.", items: { $ref: "#/components/schemas/ContextFact" } }, conflicts: { type: "array", maxItems: 32, items: { $ref: "#/components/schemas/ContextConflict" } } } },
            ContextFact: { type: "object", required: ["field", "value", "source"], properties: { field: { type: "string", minLength: 1, maxLength: 128 }, value: { type: "string", minLength: 1, maxLength: 500 }, source: { type: "string", enum: ["conversation", "trip_project"] } } },
            PlanItem: { type: "object", required: ["id", "version", "kind", "anchorRole", "type", "state", "label", "ordinal", "parentItemId"], properties: { id: { type: "string", minLength: 1, maxLength: 128 }, version: { type: "integer", minimum: 1 }, kind: { type: "string", enum: ["anchor", "leg", "activity"] }, anchorRole: { type: "string", nullable: true, enum: ["origin", "destination", "region", "required_stop", "accommodation"] }, type: { type: "string", nullable: true, enum: ["transport", "visit", "food", "rest", "accommodation"] }, state: { type: "string", enum: ["idea", "planned", "confirmed", "backup"] }, label: { type: "string", minLength: 1, maxLength: 160 }, ordinal: { type: "integer", minimum: 0 }, parentItemId: { type: "string", nullable: true, maxLength: 128 } } },
            ContextConstraints: { type: "object", required: ["version", "values"], properties: { version: { type: "integer", minimum: 1 }, values: { $ref: "#/components/schemas/PlanningJsonObject0" } }, additionalProperties: false },
            PlanningJsonObject0: { type: "object", maxProperties: 24, additionalProperties: { $ref: "#/components/schemas/PlanningJsonValue1" } },
            PlanningJsonObject1: { type: "object", maxProperties: 24, additionalProperties: { $ref: "#/components/schemas/PlanningJsonValue2" } },
            PlanningJsonObject2: { type: "object", maxProperties: 24, additionalProperties: { $ref: "#/components/schemas/PlanningJsonValue3" } },
            PlanningJsonObject3: { type: "object", maxProperties: 24, additionalProperties: { $ref: "#/components/schemas/PlanningJsonValue4" } },
            PlanningJsonObject4: { type: "object", maxProperties: 24, additionalProperties: { $ref: "#/components/schemas/PlanningJsonValue5" } },
            PlanningJsonValue1: { oneOf: [{ $ref: "#/components/schemas/PlanningJsonScalar" }, { type: "array", maxItems: 12, items: { $ref: "#/components/schemas/PlanningJsonValue2" } }, { $ref: "#/components/schemas/PlanningJsonObject1" }] },
            PlanningJsonValue2: { oneOf: [{ $ref: "#/components/schemas/PlanningJsonScalar" }, { type: "array", maxItems: 12, items: { $ref: "#/components/schemas/PlanningJsonValue3" } }, { $ref: "#/components/schemas/PlanningJsonObject2" }] },
            PlanningJsonValue3: { oneOf: [{ $ref: "#/components/schemas/PlanningJsonScalar" }, { type: "array", maxItems: 12, items: { $ref: "#/components/schemas/PlanningJsonValue4" } }, { $ref: "#/components/schemas/PlanningJsonObject3" }] },
            PlanningJsonValue4: { oneOf: [{ $ref: "#/components/schemas/PlanningJsonScalar" }, { type: "array", maxItems: 12, items: { $ref: "#/components/schemas/PlanningJsonValue5" } }, { $ref: "#/components/schemas/PlanningJsonObject4" }] },
            PlanningJsonValue5: { $ref: "#/components/schemas/PlanningJsonScalar" },
            PlanningJsonScalar: { oneOf: [{ type: "object", nullable: true, enum: [null] }, { type: "boolean" }, { type: "number" }, { type: "string", maxLength: 500 }] },
            ContextConflict: { type: "object", required: ["field", "canonicalValue", "lowerPriorityValue", "source", "priority", "material"], properties: { field: { type: "string", minLength: 1, maxLength: 128 }, canonicalValue: { type: "string", minLength: 1, maxLength: 500 }, lowerPriorityValue: { type: "string", minLength: 1, maxLength: 500 }, source: { type: "string", enum: ["legacy_project", "project_chat", "conversation_chat"] }, priority: { type: "string", enum: ["lower"] }, material: { type: "boolean", enum: [true] } } },
              PlanningAnswerDetail: { type: "object", required: ["detail"], properties: { detail: nullableReference("AnswerDetail", "Missing and foreign ownership are both null; never includes snapshots, provider payloads, or raw source material.") } },
            AnswerDetail: { type: "object", required: ["conversationId", "assistantMessageId", "content", "provenance", "annotations"], properties: { conversationId: { type: "string", minLength: 1, maxLength: 128 }, assistantMessageId: { type: "string", minLength: 1, maxLength: 128 }, content: { type: "string", maxLength: 20000 }, provenance: { type: "array", maxItems: 100, description: "Strictly increasing rank order.", items: { $ref: "#/components/schemas/PlanningProvenance" } }, annotations: { type: "array", maxItems: 20, description: "UTF-16 content ranges in non-overlapping ascending order.", items: { $ref: "#/components/schemas/PlanningAnnotation" } } } },
            PlanningProvenance: { oneOf: [{ $ref: "#/components/schemas/AvailableProvenance" }, { $ref: "#/components/schemas/UnavailableProvenance" }] },
            UnavailableProvenance: { type: "object", required: ["id", "rank", "availability", "unavailableLabel", "usedInPrompt", "citedInAnswer"], properties: { id: { type: "string", minLength: 1, maxLength: 128 }, rank: { type: "integer", minimum: 1 }, availability: { type: "string", enum: ["withdrawn"] }, unavailableLabel: { type: "string", enum: ["Nguồn này không còn khả dụng."] }, usedInPrompt: { type: "boolean" }, citedInAnswer: { type: "boolean" } }, additionalProperties: false },
            AvailableProvenance: { type: "object", required: ["id", "rank", "availability", "sourceCategory", "title", "sourceType", "url", "checkedAt", "confidenceLabel", "verificationStatus", "usedInPrompt", "citedInAnswer", "retrievalScore", "freshnessSensitive"], properties: { id: { type: "string", minLength: 1, maxLength: 128 }, rank: { type: "integer", minimum: 1 }, availability: { type: "string", enum: ["available"] }, sourceCategory: { type: "string", enum: ["knowledge", "web", "trip_context", "chat_context", "general"] }, title: { type: "string", minLength: 1, maxLength: 500 }, sourceType: { type: "string", nullable: true, maxLength: 160 }, url: { type: "string", nullable: true, format: "uri", maxLength: 2000 }, checkedAt: { type: "string", nullable: true, format: "date-time" }, confidenceLabel: { type: "string", minLength: 1, maxLength: 160 }, verificationStatus: { type: "string", enum: ["verified", "unverified"] }, usedInPrompt: { type: "boolean" }, citedInAnswer: { type: "boolean" }, retrievalScore: { type: "number", nullable: true }, freshnessSensitive: { type: "boolean" } }, additionalProperties: false },
            PlanningAnnotation: { type: "object", required: ["id", "start", "end", "text", "type", "detail"], properties: { id: { type: "string", minLength: 1, maxLength: 128 }, start: { type: "integer", minimum: 0 }, end: { type: "integer", minimum: 1 }, text: { type: "string", minLength: 1, maxLength: 2000 }, type: { type: "string", enum: ["source", "warning", "trip_fact", "action", "place", "hotel_area", "route_segment", "cost"] }, detail: { $ref: "#/components/schemas/AnnotationDetail" } }, additionalProperties: false },
            AnnotationDetail: { type: "object", required: ["type", "label"], properties: { type: { type: "string", enum: ["source", "warning", "trip_fact", "action", "place", "hotel_area", "route_segment", "cost"] }, label: { type: "string", minLength: 1, maxLength: 2000 }, section: { type: "string", minLength: 1, maxLength: 160 }, summary: { type: "string", minLength: 1, maxLength: 500 }, sourceCategory: { type: "string", enum: ["knowledge", "web", "trip_context", "chat_context", "general"] }, owner: { type: "object", required: ["table", "id"], properties: { table: { type: "string", enum: ["assistant_response_provenance"] }, id: { type: "string", minLength: 1, maxLength: 128 } }, additionalProperties: false }, detail: { type: "object", maxProperties: 6, additionalProperties: { type: "string", minLength: 1, maxLength: 160 } }, quickFacts: { type: "array", maxItems: 6, items: { type: "object", required: ["label", "value"], properties: { label: { type: "string", minLength: 1, maxLength: 160 }, value: { type: "string", minLength: 1, maxLength: 160 } }, additionalProperties: false } }, provenanceIds: { type: "array", maxItems: 6, uniqueItems: true, items: { type: "string", minLength: 1, maxLength: 128 } }, action: { $ref: "#/components/schemas/AnnotationAction" }, capability: { $ref: "#/components/schemas/AnnotationCapability" } }, additionalProperties: false },
            AnnotationAction: { type: "object", required: ["command", "label", "arguments", "anchor"], properties: { command: { type: "string", enum: ["trip_change_proposal.apply", "trip_change_proposal.dismiss"] }, label: { type: "string", minLength: 1, maxLength: 2000 }, arguments: { type: "object", maxProperties: 0, additionalProperties: false }, anchor: { type: "string", enum: ["trip-change-proposal-action.v1"] } }, additionalProperties: false },
            AnnotationCapability: { type: "object", required: ["command", "label", "available"], properties: { command: { type: "string", enum: ["trip_change_proposal.apply", "trip_change_proposal.dismiss"] }, label: { type: "string", minLength: 1, maxLength: 2000 }, available: { type: "boolean", enum: [true] } }, additionalProperties: false },
            AdminUserRosterItem: { type: "object", required: ["id", "name", "email", "image", "emailVerified", "roles", "usage"], properties: { id: { type: "string", maxLength: 128 }, name: { type: "string", nullable: true, maxLength: 512 }, email: { type: "string", nullable: true, maxLength: 512 }, image: { type: "string", nullable: true, maxLength: 2000 }, emailVerified: { type: "string", nullable: true, format: "date-time" }, roles: { type: "array", items: { type: "string", enum: ["traveler", "operator", "admin"] } }, usage: { type: "object", required: ["aiRequestCount", "inputTokens", "outputTokens"], properties: { aiRequestCount: { type: "string" }, inputTokens: { type: "string" }, outputTokens: { type: "string" } } } }, additionalProperties: false },
            AdminUserRosterPage: { type: "object", required: ["items", "nextCursor", "search"], properties: { items: { type: "array", maxItems: 25, items: { $ref: "#/components/schemas/AdminUserRosterItem" } }, nextCursor: { type: "string", nullable: true, maxLength: 512 }, search: { type: "string", maxLength: 120 } }, additionalProperties: false },
            UserRoleBody: { type: "object", required: ["role"], properties: { role: { type: "string", enum: ["operator", "admin"] } }, additionalProperties: false },
            UserRoleCommandResult: { type: "object", required: ["targetUserId", "role", "operation", "changed"], properties: { targetUserId: { type: "string", maxLength: 128 }, role: { type: "string", enum: ["operator", "admin"] }, operation: { type: "string", enum: ["grant", "revoke"] }, changed: { type: "boolean" } }, additionalProperties: false },
          SafeApiError: { type: "object", required: ["code", "message", "requestId"], properties: { code: { type: "string", enum: ["unauthorized", "forbidden", "validation_error", "csrf_invalid", "request_timeout", "internal_error"] }, message: { type: "string" }, requestId: { type: "string" }, violations: { type: "array", maxItems: 20, items: { type: "object", required: ["field", "code", "message"], properties: { field: { type: "string" }, code: { type: "string" }, message: { type: "string" } } } } } },
        },
        responses: { SafeError: { description: "Safe error envelope; never includes token, cookie, stack, SQL, or private configuration data.", content: { "application/json": { schema: { $ref: "#/components/schemas/SafeApiError" } } } } },
      },
    };
  }
}

function jsonResponse(description: string, schema: string) {
  return { description, content: { "application/json": { schema: { $ref: `#/components/schemas/${schema}` } } } };
}

function csrfHeaderParameter() {
  return { name: "X-XuyenViet-CSRF", in: "header", required: false, description: "Required for browser-session mutations; not used by the retained bearer path.", schema: { type: "string", pattern: "^[A-Za-z0-9_-]{43}$" } };
}

function nullableReference(schema: string, description: string) {
  // OAS 3.0 has no `type: null`; nullable expands this typed branch to include
  // null, and the enum restricts it to null while the other branch is the ref.
  return { oneOf: [{ type: "object", nullable: true, enum: [null] }, { $ref: `#/components/schemas/${schema}` }], description };
}
