import Link from "next/link";

const sections = [
  { title: "Nguồn đã nạp", href: "/knowledge/intake", action: "Mở nạp nguồn", states: [["Chưa xử lý", "URL chưa có phiên bản nội dung thu thập hiện hành.", "Xem đúng hàng đợi theo loại nguồn; không nhập lại cùng URL."], ["Đã xử lý", "URL đã có phiên bản nội dung thu thập hiện hành.", "Xem lần thu thập hoặc tác vụ xử lý nếu cần; trạng thái này không nói thẻ đã hoạt động hoặc AI đã dùng."], ["Đã gỡ", "Nguồn không còn đủ điều kiện sử dụng.", "Không nhập lại như nguồn mới; hệ thống sẽ đánh giá lại bằng chứng và thẻ liên quan."]] },
  { title: "Thu thập và xử lý kỹ thuật", href: "/knowledge/facebook-captures", action: "Mở hàng đợi Facebook", states: [["Chờ / đang chạy", "Tác vụ đang chờ tiến trình nền hoặc đang xử lý phiên bản nội dung thu thập.", "Chờ; không tạo thẻ thủ công để thay quy trình."], ["Hoàn thành", "Việc tìm ứng viên đã kết thúc và mọi ứng viên đã có kết quả hoặc lỗi.", "Xem số ứng viên và từng kết quả; tác vụ hoàn thành không có nghĩa mọi thẻ được xuất bản."], ["Lỗi", "Tác vụ kỹ thuật không hoàn thành.", "Đọc chi tiết; chỉ yêu cầu thu thập lại hoặc chạy lại khi màn hình cho phép."]] },
  { title: "Bằng chứng YouTube", href: "/knowledge/youtube-captures", action: "Mở hàng đợi YouTube", states: [["Bằng chứng có cấu trúc", "Video đã có bằng chứng giới hạn với mốc thời gian, độ tin cậy và điều kiện.", "Dùng bằng chứng để hiểu nguồn; nó không tự là thẻ đang hoạt động hoặc thông tin đã xác minh."], ["Tác vụ kỹ thuật", "Nếu có tác vụ xử lý, trạng thái và số ứng viên cho biết tiến độ kỹ thuật.", "Không suy ra kết quả xuất bản từ trạng thái tác vụ; theo dõi thẻ và yêu cầu vận hành riêng."]] },
  { title: "Vòng đời thẻ và chỉ mục", href: "/knowledge/cards", action: "Mở thẻ tri thức", states: [["Bản nháp / chờ vận hành", "Thẻ chưa đủ điều kiện để dùng trả lời hoặc đang chờ một quyết định hợp lệ.", "Mở yêu cầu vận hành hiện hành khi có; không coi đây là hàng đợi phê duyệt chung."], ["Đang hoạt động", "Thẻ chỉ được AI truy xuất khi bằng chứng/nguồn còn hợp lệ và không cần xác minh thêm.", "Theo dõi điều kiện, độ mới và trạng thái chỉ mục; thẻ hoạt động không biến nguồn cộng đồng thành nguồn chính thức."], ["Tạm ẩn / lưu trữ / từ chối", "Thẻ không dùng để trả lời thông thường.", "Không khôi phục bằng thao tác ngoài luồng; dùng quyết định hiện có hoặc chuyển tuyến."], ["Chỉ mục cũ hoặc chưa có", "Chỉ mục tìm kiếm chưa khớp phiên bản thẻ hiện hành.", "Chờ tiến trình nền đồng bộ; hệ thống vẫn tự kiểm tra điều kiện an toàn trước khi dùng thẻ."]] },
  { title: "Yêu cầu vận hành", href: "/knowledge/recommendations", action: "Mở yêu cầu", states: [["Chưa xử lý", "Yêu cầu đang mở và còn khớp với thẻ cùng bằng chứng hiện hành.", "Mở chi tiết, đối chiếu bằng chứng và chọn một quyết định được hiển thị."], ["Đã xử lý", "Yêu cầu đã có kết quả xử lý.", "Không xử lý lại; kiểm tra thẻ hoặc yêu cầu mới nếu cần."], ["Không còn hiệu lực", "Yêu cầu bị thay thế hoặc không còn khớp phiên bản hiện tại.", "Không thao tác tiếp; tìm yêu cầu đang mở trên thẻ hiện hành."], ["Lấy mẫu", "Đây là kiểm soát chất lượng, không phải cổng xuất bản bắt buộc.", "Ghi nhận kết quả theo thao tác được hiển thị; không dùng lấy mẫu để suy diễn quyết định AI ban đầu."]] },
];

export default function DataStatesGuidePage() {
  return <div><header><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#8c4f13]">Hướng dẫn 02</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Trạng thái dữ liệu và việc cần làm</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-[#4f625a]">Dùng trang này để chọn thao tác an toàn. Nếu trạng thái không có hành động được hiển thị trong admin, không tự bỏ qua quy trình hoặc tạo thao tác ngoài luồng.</p></header><div className="mt-8 grid gap-6">{sections.map((section) => <section className="rounded-[1.5rem] border border-[#d8c9ad] bg-white/75 p-5 sm:p-6" key={section.title}><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><h2 className="text-2xl font-semibold tracking-[-0.03em] text-[#17342c]">{section.title}</h2><Link className="font-semibold text-[#1f5f46] underline underline-offset-4" href={section.href}>{section.action}</Link></div><div className="mt-5 grid gap-3">{section.states.map(([state, meaning, next]) => <article className="rounded-2xl border border-[#e2d3ba] bg-[#fbf7ed] p-4" key={state}><h3 className="font-semibold text-[#17342c]">{state}</h3><p className="mt-2 leading-6 text-[#4f625a]"><strong className="text-[#17342c]">Ý nghĩa: </strong>{meaning}</p><p className="mt-2 leading-6 text-[#4f625a]"><strong className="text-[#17342c]">Nên làm: </strong>{next}</p></article>)}</div></section>)}</div></div>;
}
