import { getApprovedKnowledgeIndexStatuses, getKnowledgeCard, listKnowledgeCards, type ApprovedKnowledgeIndexStatus, type KnowledgeDraftReviewCard } from "./knowledge-draft-review";
import { getKnowledgeRecommendationDetail, getKnowledgeRecommendationWorkStatusCounts, listKnowledgeRecommendations, resolveKnowledgeRecommendation, type KnowledgeRecommendationListItem } from "./knowledge-recommendations";
import { getDb } from "./client";
import { knowledgeCards, knowledgeRecommendations, users } from "./schema";
import { eq } from "drizzle-orm";
import type { AdminKnowledgeReviewPort } from "@xuyenviet/domain";

const text = (value: unknown, maximum: number) => typeof value === "string" ? value.replace(/\s+/g, " ").trim().slice(0, maximum) : "";
const date = (value: Date) => value.toISOString();
type RecommendationDetail = NonNullable<Awaited<ReturnType<typeof getKnowledgeRecommendationDetail>>>;

const source = (value: KnowledgeDraftReviewCard["sources"][number]) => ({ id: value.id, label: text(value.label, 160), kind: value.kind, sourceType: value.sourceType, verificationStatus: value.verificationStatus, supportLevel: value.supportLevel, publisher: value.publisher ? text(value.publisher, 160) : null, collectedDate: value.collectedDate ?? null, official: value.official, partner: value.partner });
const card = (value: KnowledgeDraftReviewCard, indexStatus: ApprovedKnowledgeIndexStatus | null = null) => ({ id: value.id, type: value.type, title: text(value.title, 160), locationName: value.locationName ? text(value.locationName, 160) : null, routeSegment: value.routeSegment ? text(value.routeSegment, 160) : null, summary: text(value.summary, 1200), conditions: value.conditions.map((item) => text(item, 500)).filter(Boolean).slice(0, 20), practicalDetails: safeDetails(value.practicalDetails), tags: value.tags.map((item) => text(item, 40)).filter(Boolean).slice(0, 12), confidence: value.confidence, freshnessSensitive: value.freshnessSensitive, lifecycleState: value.lifecycleState, knowledgeState: value.knowledgeState, verificationRequirement: value.verificationRequirement, updatedAt: date(value.updatedAt), createdAt: date(value.createdAt), sources: value.sources.map(source), indexStatus: indexStatus ? index(indexStatus) : null });
function safeDetails(value: unknown): Record<string, string | string[]> { if (!value || typeof value !== "object" || Array.isArray(value)) return {}; const result: Record<string, string | string[]> = {}; for (const [key, item] of Object.entries(value).slice(0, 20)) { if (typeof item === "string") result[text(key, 60)] = text(item, 500); else if (Array.isArray(item) && item.every((entry): entry is string => typeof entry === "string")) result[text(key, 60)] = item.slice(0, 40).map((entry) => text(entry, 500)); } return result; }
export function createPostgresAdminKnowledgeReviewPort(): AdminKnowledgeReviewPort { return {
  async listCards(input) { const cards = await listKnowledgeCards(input.lifecycleState); const query = input.q?.toLocaleLowerCase(); const selected = cards.filter((item) => !query || `${item.title} ${item.summary}`.toLocaleLowerCase().includes(query)).slice(0, 200); const activeStatuses = input.lifecycleState === "active" ? await getApprovedKnowledgeIndexStatuses(selected.map((item) => item.id)) : new Map(); return { items: selected.map((item) => card(item, activeStatuses.get(item.id) ?? null)) }; },
  async getCard(id) { const value = await getKnowledgeCard(id); if (!value) return null; const status = value.lifecycleState === "active" ? (await getApprovedKnowledgeIndexStatuses([id])).get(id) ?? null : null; return card(value, status); },
  async listRecommendations(input) { const query = input as Parameters<typeof listKnowledgeRecommendations>[0]; const [items, counts] = await Promise.all([listKnowledgeRecommendations(query), getKnowledgeRecommendationWorkStatusCounts()]); return { items: items.map(recommendation), counts }; },
  async getRecommendation(id) { const value = await getKnowledgeRecommendationDetail(id); return value ? recommendationDetail(value) : null; },
  async resolveRecommendation(id, input, actor) { const [current] = await getDb().select({ contentVersion: knowledgeCards.contentVersion, evidenceSetRevision: knowledgeCards.evidenceSetRevision }).from(knowledgeRecommendations).innerJoin(knowledgeCards, eq(knowledgeCards.id, knowledgeRecommendations.knowledgeCardId)).where(eq(knowledgeRecommendations.id, id)).limit(1); if (!current) return { status: "unavailable" as const }; return resolveKnowledgeRecommendation({ recommendationId: id, expectedContentVersion: current.contentVersion, expectedEvidenceSetRevision: current.evidenceSetRevision, action: input.action, highSeverity: input.highSeverity, actor: await auditActor(actor.userId) }); },
}; }
async function auditActor(userId: string) { const [user] = await getDb().select({ email: users.email }).from(users).where(eq(users.id, userId)).limit(1); if (!user?.email) throw new Error("audit actor unavailable"); return { userId, email: user.email }; }
function index(value: ApprovedKnowledgeIndexStatus) { return { state: value.state, label: text(value.label, 160), documentStatus: value.documentStatus, indexedAt: value.indexedAt ? date(value.indexedAt) : null }; }
function recommendation(value: KnowledgeRecommendationListItem) { return { id: value.id, status: value.status, resolution: value.resolution, workType: value.workType, priority: value.priority, createdAt: date(value.createdAt), card: { id: value.card.id, title: text(value.card.title, 160), summary: text(value.card.summary, 1200), lifecycleState: value.card.lifecycleState, knowledgeState: value.card.knowledgeState, verificationRequirement: value.card.verificationRequirement } }; }
function recommendationDetail(value: RecommendationDetail) { const base = recommendation(value); return { ...base, card: { ...base.card, type: value.card.type, locationName: value.card.locationName ? text(value.card.locationName, 160) : null, routeSegment: value.card.routeSegment ? text(value.card.routeSegment, 160) : null, tags: value.card.tags.map((item) => text(item, 40)).slice(0, 12), freshnessSensitive: value.card.freshnessSensitive }, evidence: value.evidence.slice(0, 4).map((item) => ({ quote: text(item.quoteText, 500), conditions: item.conditions.map((entry) => text(entry, 160)).slice(0, 10), supportLevel: item.supportLevel, displayPolicy: item.displayPolicy, capturedAt: date(item.capturedAt), sourceLabel: text(item.sourceLabel, 160), sourceKind: item.sourceKind, facebookReviewId: item.facebookReviewId })) }; }
