import { getApprovedKnowledgeCard, getApprovedKnowledgeIndexStatuses, getKnowledgeDraftForReview, listApprovedKnowledgeCardsWithIndexStatus, listKnowledgeDraftsForReview, approveKnowledgeDraft, approveKnowledgeDraftBatch, rejectKnowledgeDraft, updateKnowledgeDraft, type ApprovedKnowledgeIndexStatus, type KnowledgeDraftReviewCard, type KnowledgeDraftUpdateInput } from "./knowledge-draft-review";
import { getKnowledgeRecommendationDetail, getKnowledgeRecommendationWorkStatusCounts, listKnowledgeRecommendations, resolveKnowledgeRecommendation, type KnowledgeRecommendationListItem } from "./knowledge-recommendations";
import { getDb } from "./client";
import { users } from "./schema";
import { eq } from "drizzle-orm";
import { searchApprovedKnowledgeWithCandidateCount } from "./knowledge-search";
import type { AdminKnowledgeReviewPort } from "@xuyenviet/domain";

const text = (value: unknown, maximum: number) => typeof value === "string" ? value.replace(/\s+/g, " ").trim().slice(0, maximum) : "";
const date = (value: Date) => value.toISOString();
type ReviewCard = Omit<KnowledgeDraftReviewCard, "suggestion">;
type RecommendationDetail = NonNullable<Awaited<ReturnType<typeof getKnowledgeRecommendationDetail>>>;

const source = (value: KnowledgeDraftReviewCard["sources"][number]) => ({ id: value.id, label: text(value.label, 160), kind: value.kind, sourceType: value.sourceType, verificationStatus: value.verificationStatus, supportLevel: value.supportLevel, publisher: value.publisher ? text(value.publisher, 160) : null, collectedDate: value.collectedDate ?? null, official: value.official, partner: value.partner });
const card = (value: ReviewCard) => ({ id: value.id, type: value.type, title: text(value.title, 160), locationName: value.locationName ? text(value.locationName, 160) : null, routeSegment: value.routeSegment ? text(value.routeSegment, 160) : null, summary: text(value.summary, 1200), practicalDetails: safeDetails(value.practicalDetails), tags: value.tags.map((item) => text(item, 40)).filter(Boolean).slice(0, 12), confidence: value.confidence, freshnessSensitive: value.freshnessSensitive, lifecycleState: value.lifecycleState, knowledgeState: value.knowledgeState, verificationRequirement: value.verificationRequirement, updatedAt: date(value.updatedAt), createdAt: date(value.createdAt), sources: value.sources.map(source) });
function safeDetails(value: unknown): Record<string, string | string[]> { if (!value || typeof value !== "object" || Array.isArray(value)) return {}; const result: Record<string, string | string[]> = {}; for (const [key, item] of Object.entries(value).slice(0, 20)) { if (typeof item === "string") result[text(key, 60)] = text(item, 500); else if (Array.isArray(item) && item.every((entry): entry is string => typeof entry === "string")) result[text(key, 60)] = item.slice(0, 40).map((entry) => text(entry, 500)); } return result; }
function draft(value: KnowledgeDraftReviewCard) { return { ...card(value), suggestion: value.suggestion ? { action: value.suggestion.action, beforeSummary: value.suggestion.beforeSummary ? text(value.suggestion.beforeSummary, 1200) : null, afterSummary: value.suggestion.afterSummary ? text(value.suggestion.afterSummary, 1200) : null, conflictSummary: value.suggestion.conflictSummary ? text(value.suggestion.conflictSummary, 1200) : null, rationale: value.suggestion.rationale ? text(value.suggestion.rationale, 1200) : null, targetCard: value.suggestion.targetCard ? { id: value.suggestion.targetCard.id, title: text(value.suggestion.targetCard.title, 160) } : null } : null }; }
export function createPostgresAdminKnowledgeReviewPort(): AdminKnowledgeReviewPort { return {
  async listDrafts() { return { items: (await listKnowledgeDraftsForReview()).map(draft) }; },
  async getDraft(id) { const value = await getKnowledgeDraftForReview(id); return value ? draft(value) : null; },
  async updateDraft(id, input, actor) { return updateKnowledgeDraft(id, input as KnowledgeDraftUpdateInput, await auditActor(actor.userId)); },
  async rejectDraft(id, actor) { return rejectKnowledgeDraft(id, await auditActor(actor.userId)); },
  async approveDraft(id, actor, expectedUpdatedAt) { return approveKnowledgeDraft(id, await auditActor(actor.userId), expectedUpdatedAt); },
  async approveDraftBatch(ids, actor) { return approveKnowledgeDraftBatch(ids, await auditActor(actor.userId)); },
  async listApproved(query) { if (query) { const found = await searchApprovedKnowledgeWithCandidateCount(query, { limit: 10 }); const statuses = await getApprovedKnowledgeIndexStatuses(found.results.map((item) => item.id)); return { candidateCount: found.candidateCount, items: found.results.map((item) => ({ ...card({ ...item, sources: [], createdAt: new Date(), updatedAt: new Date() }), indexStatus: statuses.get(item.id) ? index(statuses.get(item.id)!) : null })) }; } const items = await listApprovedKnowledgeCardsWithIndexStatus(); return { candidateCount: items.length, items: items.map((item) => ({ ...card(item), indexStatus: index(item.indexStatus) })) }; },
  async getApproved(id) { const value = await getApprovedKnowledgeCard(id); if (!value) return null; const status = (await getApprovedKnowledgeIndexStatuses([id])).get(id); return { ...card(value), indexStatus: status ? index(status) : null }; },
  async listRecommendations(input) { const query = input as Parameters<typeof listKnowledgeRecommendations>[0]; const [items, counts] = await Promise.all([listKnowledgeRecommendations(query), getKnowledgeRecommendationWorkStatusCounts()]); return { items: items.map(recommendation), counts }; },
  async getRecommendation(id) { const value = await getKnowledgeRecommendationDetail(id); return value ? recommendationDetail(value) : null; },
  async resolveRecommendation(id, input, actor) { const request = input as { expectedContentVersion: number; expectedEvidenceSetRevision: number; action: import("./schema").KnowledgeRecommendationAction; highSeverity?: boolean }; return resolveKnowledgeRecommendation({ recommendationId: id, expectedContentVersion: request.expectedContentVersion, expectedEvidenceSetRevision: request.expectedEvidenceSetRevision, action: request.action, highSeverity: request.highSeverity, actor: await auditActor(actor.userId) }); },
}; }
async function auditActor(userId: string) { const [user] = await getDb().select({ email: users.email }).from(users).where(eq(users.id, userId)).limit(1); if (!user?.email) throw new Error("audit actor unavailable"); return { userId, email: user.email }; }
function index(value: ApprovedKnowledgeIndexStatus) { return { state: value.state, label: text(value.label, 160), documentStatus: value.documentStatus, indexedAt: value.indexedAt ? date(value.indexedAt) : null }; }
function recommendation(value: KnowledgeRecommendationListItem) { return { id: value.id, status: value.status, resolution: value.resolution, workType: value.workType, priority: value.priority, contentVersion: value.contentVersion, evidenceSetRevision: value.evidenceSetRevision, createdAt: date(value.createdAt), card: { id: value.card.id, title: text(value.card.title, 160), summary: text(value.card.summary, 1200), lifecycleState: value.card.lifecycleState, knowledgeState: value.card.knowledgeState, verificationRequirement: value.card.verificationRequirement } }; }
function recommendationDetail(value: RecommendationDetail) { const base = recommendation({ ...value, card: { ...value.card, contentVersion: value.contentVersion, evidenceSetRevision: value.evidenceSetRevision } }); return { ...base, card: { ...base.card, type: value.card.type, locationName: value.card.locationName ? text(value.card.locationName, 160) : null, routeSegment: value.card.routeSegment ? text(value.card.routeSegment, 160) : null, tags: value.card.tags.map((item) => text(item, 40)).slice(0, 12), freshnessSensitive: value.card.freshnessSensitive }, evidence: value.evidence.slice(0, 4).map((item) => ({ quote: text(item.quoteText, 500), conditions: item.conditions.map((entry) => text(entry, 160)).slice(0, 10), supportLevel: item.supportLevel, displayPolicy: item.displayPolicy, capturedAt: date(item.capturedAt), sourceLabel: text(item.sourceLabel, 160), sourceKind: item.sourceKind, facebookReviewId: item.facebookReviewId })) }; }
