import { count, desc, eq, isNull, or, sql } from "drizzle-orm";
import type { AdminFacebookCapture, AdminFacebookCaptureCommandResult, AdminFacebookCaptureDetail, AdminFacebookCaptureQueue, AdminFacebookCaptureQueueStatus, RequestPrincipal } from "@xuyenviet/contracts";
import { adminFacebookCapturePageSize } from "@xuyenviet/contracts";
import type { AdminFacebookCapturePort } from "@xuyenviet/domain";
import { getDb } from "./client";
import { facebookCaptureReviews, knowledgeIngestionJobs, sourceCaptureVersions, sources } from "./schema";

export function createPostgresAdminFacebookCapturePort(): AdminFacebookCapturePort { return { list, detail, recapture, rerunIngestion }; }

async function list(input: { status: AdminFacebookCaptureQueueStatus; page: number }): Promise<AdminFacebookCaptureQueue> {
  const db = getDb(); const offset = (input.page - 1) * adminFacebookCapturePageSize;
  const rows = await query().orderBy(desc(knowledgeIngestionJobs.updatedAt), desc(facebookCaptureReviews.updatedAt)).limit(adminFacebookCapturePageSize).offset(offset);
  const items = rows.map(project).filter((item) => queueStatus(item.ingestionJob?.status) === input.status);
  const [total] = await db.select({ count: count() }).from(facebookCaptureReviews);
  const counts: Record<AdminFacebookCaptureQueueStatus, number> = { in_progress: 0, needs_attention: 0, failed: 0, published: 0, suppressed: 0 };
  for (const row of rows) counts[queueStatus(row.status)] += 1;
  return { status: input.status, page: input.page, pageSize: adminFacebookCapturePageSize, totalCount: Number(total?.count ?? 0), counts, items };
}
async function detail(id: string): Promise<AdminFacebookCaptureDetail | null> { const [row] = await query().where(eq(facebookCaptureReviews.id, id)).limit(1); return row ? { ...project(row), canRecapture: ["needs_review", "extraction_failed", "rejected"].includes(row.reviewStatus), canRerunIngestion: row.status === "failed" } : null; }
async function recapture(_actor: RequestPrincipal, _id: string, _reason: string): Promise<AdminFacebookCaptureCommandResult> { throw new Error("Facebook capture lifecycle commands require Story 15.3."); }
async function rerunIngestion(_actor: RequestPrincipal, _id: string): Promise<AdminFacebookCaptureCommandResult> { throw new Error("Facebook capture lifecycle commands require Story 15.3."); }
function query() { return getDb().select({ id: facebookCaptureReviews.id, reviewStatus: facebookCaptureReviews.status, updatedAt: facebookCaptureReviews.updatedAt, sourceLabel: sources.label, sourceUrl: sources.url, canonicalUrl: sources.canonicalUrl, captureMethod: sql<string | null>`${sourceCaptureVersions.rawMetadata}->>'captureMethod'`, capturedAt: sql<string | null>`${sourceCaptureVersions.rawMetadata}->>'capturedAt'`, groupName: sql<string | null>`${sourceCaptureVersions.rawMetadata}->>'groupName'`, authorText: sql<string | null>`${sourceCaptureVersions.rawMetadata}->>'authorText'`, postCreatedAt: sql<string | null>`${sourceCaptureVersions.rawMetadata}->>'postCreatedAt'`, rawPresent: sql<boolean>`length(btrim(coalesce(${sourceCaptureVersions.rawText}, ''))) > 0`, jobId: knowledgeIngestionJobs.id, status: knowledgeIngestionJobs.status, discoveryTerminal: knowledgeIngestionJobs.discoveryTerminal, jobUpdatedAt: knowledgeIngestionJobs.updatedAt, lastErrorCode: knowledgeIngestionJobs.lastErrorCode, candidateCount: knowledgeIngestionJobs.candidateCount, completedCandidateCount: knowledgeIngestionJobs.completedCandidateCount, needsOperatorCandidateCount: knowledgeIngestionJobs.needsOperatorCandidateCount, failedCandidateCount: knowledgeIngestionJobs.failedCandidateCount }).from(facebookCaptureReviews).innerJoin(sources, eq(sources.id, facebookCaptureReviews.sourceId)).leftJoin(sourceCaptureVersions, eq(sourceCaptureVersions.id, facebookCaptureReviews.captureVersionId)).leftJoin(knowledgeIngestionJobs, eq(knowledgeIngestionJobs.captureVersionId, facebookCaptureReviews.captureVersionId)); }
function project(row: Awaited<ReturnType<ReturnType<typeof query>["limit"]>>[number]): AdminFacebookCapture { const job = row.jobId && row.status && row.jobUpdatedAt ? { status: row.status, discoveryTerminal: row.discoveryTerminal ?? false, updatedAt: row.jobUpdatedAt.toISOString(), lastErrorCode: row.lastErrorCode, candidateCount: row.candidateCount ?? 0, completedCandidateCount: row.completedCandidateCount ?? 0, needsOperatorCandidateCount: row.needsOperatorCandidateCount ?? 0, failedCandidateCount: row.failedCandidateCount ?? 0 } : null; return { id: row.id, sourceLabel: row.sourceLabel, displayUrl: row.canonicalUrl ?? row.sourceUrl, reviewStatus: row.reviewStatus, captureMethod: row.captureMethod, capturedAt: row.capturedAt, groupName: row.groupName, authorText: row.authorText, postCreatedAt: row.postCreatedAt, updatedAt: row.updatedAt.toISOString(), ingestionJob: job, operationState: job ? null : row.rawPresent ? "awaiting_ingestion_job" : "recapture_pending" }; }
function queueStatus(status: "queued" | "running" | "completed" | "failed" | null | undefined): AdminFacebookCaptureQueueStatus { return status === "failed" ? "failed" : status === "completed" ? "published" : "in_progress"; }
