import { and, eq } from "drizzle-orm";
import { sanitizeStoredPlanningAnnotations } from "@xuyenviet/domain";

import { createSystemAuditActor, toUserAuditActor } from "./actors";
import { recordAuditEvent, recordPlanHistory } from "./audit-writers";
import { getDb } from "./client";
import { formatAssistantMessageProvenance } from "./provenance";
import { assistantResponseProvenance, conversations, messages, tripChangeProposals, tripPlanItems, tripProjectConstraints, tripProjects, users, type TripPlanAnchorRole, type TripPlanItemKind, type TripPlanItemState, type TripPlanItemType } from "./schema";
import { changeInternalTripPlanItemStateInTransaction, createTripPlanItemInTransaction, deleteTripPlanItemInTransaction, normalizeConstraints, normalizePlanItem, reorderTripPlanItemInTransaction, updateTripPlanItemInTransaction, upsertInternalTripProjectConstraintsInTransaction, type InternalPlanItemInput, type TripPlanCommandTransaction } from "./trip-plan-commands";
import { validatePlanReferencesRules, type PlanItemReference } from "./plan-references";

const validStates: readonly TripPlanItemState[] = ["idea", "planned", "confirmed", "backup"];
const recognizedOrderingPreconditionKeys = new Set(["parentItemId", "ordinal", "expectedChangedItemVersions"]);
const maxSafeSummaryBytes = 8000;

export type AnnotationActionBinding = { conversationId: string; assistantMessageId: string; annotationId: string; command: "trip_change_proposal.apply" | "trip_change_proposal.dismiss" };
export type ProposalCommandInput = { tripProjectId: string; proposalId: string; requiredSourceAssistantMessageId?: string; annotationBinding?: AnnotationActionBinding };
export type ApplyTripChangeProposalResult = { success: true; aggregateVersion: number; proposal: TerminalProposalRow } | { success: false; reason: "not_found" | "refresh_required" | "expired" };
export type DismissTripChangeProposalResult = { success: true; proposal: TerminalProposalRow } | { success: false; reason: "not_found" | "expired" };
export type ExpireTripChangeProposalInput = { tripProjectId: string; proposalId: string; now?: Date };
export type ExpireTripChangeProposalResult = { success: true; proposal: TerminalProposalRow } | { success: false; reason: "not_found" };
export type TerminalProposalRow = { id: string; userId: string; status: "pending" | "applied" | "dismissed" | "expired"; rationale: string; operations: unknown; alternatives: unknown; expiresAt: Date | null; createdAt: Date; terminalTimestamp: Date | null; affectedItems: ProposalAffectedItem[]; beforeAfter: ProposalBeforeAfter[] };
export type ProposalAffectedItem = { itemId: string; kind: TripPlanItemKind; label: string; change: "create" | "update" | "remove" | "reorder" | "change-state" | "upsert-constraints" };
export type ProposalBeforeAfter = { operation: string; before: string | null; after: string | null };

class ProposalOperationFailure extends Error { constructor(readonly reason: "refresh_required" | "not_found" | "expired") { super(reason); } }

export async function applyTripChangeProposal(userId: string, input: ProposalCommandInput): Promise<ApplyTripChangeProposalResult> {
  try {
    return await getDb().transaction(async (transaction) => {
      const actor = await loadActor(transaction, userId); if (!actor) return { success: false, reason: "not_found" } as const;
      const [project] = await transaction.select({ aggregateVersion: tripProjects.aggregateVersion }).from(tripProjects).where(and(eq(tripProjects.id, input.tripProjectId), eq(tripProjects.userId, userId))).limit(1).for("update");
      if (!project) return { success: false, reason: "not_found" } as const;
      const proposal = await lockProposal(transaction, userId, input); if (!proposal) return { success: false, reason: "not_found" } as const;
      if (input.annotationBinding && !await hasCurrentAnnotationActionBinding(transaction, userId, input.tripProjectId, input.annotationBinding)) return { success: false, reason: "not_found" } as const;
      if (proposal.status !== "pending") return { success: false, reason: "not_found" } as const;
      const now = new Date();
      if (proposal.expiresAt && proposal.expiresAt <= now) { await expireTripChangeProposalInTransaction(transaction, { tripProjectId: input.tripProjectId, proposalId: input.proposalId, now }); return { success: false, reason: "expired" } as const; }
      if (project.aggregateVersion !== proposal.expectedAggregateVersion) return { success: false, reason: "refresh_required" } as const;
      const items = await transaction.select().from(tripPlanItems).where(and(eq(tripPlanItems.tripProjectId, input.tripProjectId), eq(tripPlanItems.userId, userId))).for("update");
      const itemById = new Map(items.map((item) => [item.id, item]));
      const summaryItems = new Map(itemById);
      const operations = Array.isArray(proposal.operations) ? proposal.operations : [];
      const expectedItemVersions = proposal.expectedItemVersions as Record<string, number> | null;
      if (validateOperationFences(operations, itemById, expectedItemVersions, proposal.orderingPreconditions) || detectCrossOperationBackupCycle(operations, items, input.tripProjectId)) return { success: false, reason: "refresh_required" } as const;
      const [constraints] = await transaction.select({ version: tripProjectConstraints.version }).from(tripProjectConstraints).where(and(eq(tripProjectConstraints.tripProjectId, input.tripProjectId), eq(tripProjectConstraints.userId, userId))).limit(1);
      let aggregateVersion = project.aggregateVersion;
      for (const operation of operations) { const result = await executeOperation(transaction, actor, input.tripProjectId, aggregateVersion, operation, itemById, constraints?.version ?? null, expectedItemVersions); if (!result.success) throw new ProposalOperationFailure(result.reason); aggregateVersion = result.aggregateVersion; }
      const terminalTimestamp = new Date();
      await transaction.update(tripChangeProposals).set({ status: "applied", terminalTimestamp, updatedAt: terminalTimestamp }).where(eq(tripChangeProposals.id, proposal.id));
      const summary = proposalSummary(operations, summaryItems);
      await recordPlanHistory({ tripProjectId: input.tripProjectId, userId, proposalId: proposal.id, actor: toUserAuditActor(actor), operationClass: "apply", affectedItemReferences: summary.affectedItems, safeBeforeAfterSummary: boundBeforeAfterSummary(summary.beforeAfter) }, transaction);
      await recordAuditEvent({ actor: toUserAuditActor(actor), operation: "apply", targetType: "trip_change_proposal", targetId: proposal.id, afterSummary: JSON.stringify({ tripProjectId: input.tripProjectId, proposalId: proposal.id, aggregateVersion }) }, transaction);
      return { success: true, aggregateVersion, proposal: terminal(proposal, "applied", terminalTimestamp, summary) } as const;
    });
  } catch (error) { if (error instanceof ProposalOperationFailure) return { success: false, reason: error.reason }; if (error instanceof Error && (error.message.startsWith("Invalid trip plan") || error.message.startsWith("Invalid trip constraints"))) return { success: false, reason: "refresh_required" }; throw error; }
}

export async function dismissTripChangeProposal(userId: string, input: ProposalCommandInput): Promise<DismissTripChangeProposalResult> {
  return getDb().transaction(async (transaction) => {
    const actor = await loadActor(transaction, userId); if (!actor) return { success: false, reason: "not_found" } as const;
    const proposal = await lockProposal(transaction, userId, input); if (!proposal) return { success: false, reason: "not_found" } as const;
    if (proposal.status !== "pending") { const items = await loadPlanItems(transaction, input.tripProjectId, userId); const summary = proposalSummary(Array.isArray(proposal.operations) ? proposal.operations : [], new Map(items.map((item) => [item.id, item]))); return input.annotationBinding ? { success: false, reason: "not_found" } as const : { success: true, proposal: terminal(proposal, proposal.status, proposal.terminalTimestamp, summary) } as const; }
    if (input.annotationBinding && !await hasCurrentAnnotationActionBinding(transaction, userId, input.tripProjectId, input.annotationBinding)) return { success: false, reason: "not_found" } as const;
    const now = new Date(); if (proposal.expiresAt && proposal.expiresAt <= now) { await expireTripChangeProposalInTransaction(transaction, { tripProjectId: input.tripProjectId, proposalId: proposal.id, now }); return { success: false, reason: "expired" } as const; }
    const terminalTimestamp = new Date(); await transaction.update(tripChangeProposals).set({ status: "dismissed", terminalTimestamp, updatedAt: terminalTimestamp }).where(eq(tripChangeProposals.id, proposal.id));
    const items = await loadPlanItems(transaction, input.tripProjectId, userId);
    const summary = proposalSummary(Array.isArray(proposal.operations) ? proposal.operations : [], new Map(items.map((item) => [item.id, item])));
    await recordPlanHistory({ tripProjectId: input.tripProjectId, userId, proposalId: proposal.id, actor: toUserAuditActor(actor), operationClass: "dismiss", affectedItemReferences: summary.affectedItems, safeBeforeAfterSummary: boundBeforeAfterSummary(summary.beforeAfter) }, transaction);
    await recordAuditEvent({ actor: toUserAuditActor(actor), operation: "dismiss", targetType: "trip_change_proposal", targetId: proposal.id, afterSummary: JSON.stringify({ tripProjectId: input.tripProjectId, proposalId: proposal.id }) }, transaction);
    return { success: true, proposal: terminal(proposal, "dismissed", terminalTimestamp, summary) } as const;
  });
}

export async function executeAnnotationProposalAction(userId: string, binding: AnnotationActionBinding) {
  const [match, duplicate] = await getDb().transaction(async (transaction) => {
    const matches = await transaction.select({ id: tripChangeProposals.id, tripProjectId: tripChangeProposals.tripProjectId }).from(tripChangeProposals).innerJoin(conversations, and(eq(conversations.tripProjectId, tripChangeProposals.tripProjectId), eq(conversations.id, binding.conversationId), eq(conversations.userId, userId))).where(and(eq(tripChangeProposals.userId, userId), eq(tripChangeProposals.status, "pending"), eq(tripChangeProposals.sourceAssistantMessageId, binding.assistantMessageId))).limit(2).for("update");
    return [matches[0] ?? null, matches.length !== 1] as const;
  });
  if (duplicate || !match) return { success: false as const, reason: "not_found" as const };
  const input = { tripProjectId: match.tripProjectId, proposalId: match.id, requiredSourceAssistantMessageId: binding.assistantMessageId, annotationBinding: binding };
  return binding.command === "trip_change_proposal.apply" ? applyTripChangeProposal(userId, input) : dismissTripChangeProposal(userId, input);
}

export async function expireTripChangeProposal(input: ExpireTripChangeProposalInput): Promise<ExpireTripChangeProposalResult> { return getDb().transaction((transaction) => expireTripChangeProposalInTransaction(transaction, input)); }
export async function expireTripChangeProposalInTransaction(transaction: TripPlanCommandTransaction, input: ExpireTripChangeProposalInput): Promise<ExpireTripChangeProposalResult> {
  const now = input.now ?? new Date(); const [proposal] = await transaction.select({ id: tripChangeProposals.id, tripProjectId: tripChangeProposals.tripProjectId, userId: tripChangeProposals.userId, status: tripChangeProposals.status, rationale: tripChangeProposals.rationale, operations: tripChangeProposals.operations, alternatives: tripChangeProposals.alternatives, expiresAt: tripChangeProposals.expiresAt, createdAt: tripChangeProposals.createdAt, terminalTimestamp: tripChangeProposals.terminalTimestamp }).from(tripChangeProposals).where(and(eq(tripChangeProposals.id, input.proposalId), eq(tripChangeProposals.tripProjectId, input.tripProjectId))).limit(1).for("update");
  if (!proposal) return { success: false, reason: "not_found" }; if (proposal.status !== "pending" || !proposal.expiresAt || proposal.expiresAt > now) { const items = await loadPlanItems(transaction, proposal.tripProjectId, proposal.userId); return { success: true, proposal: terminal(proposal, proposal.status, proposal.terminalTimestamp, proposalSummary(Array.isArray(proposal.operations) ? proposal.operations : [], new Map(items.map((item) => [item.id, item])))) }; }
  await transaction.update(tripChangeProposals).set({ status: "expired", terminalTimestamp: now, updatedAt: now }).where(eq(tripChangeProposals.id, proposal.id)); const actor = createSystemAuditActor("system-trip-planning");
  const items = await loadPlanItems(transaction, proposal.tripProjectId, proposal.userId); const summary = proposalSummary(Array.isArray(proposal.operations) ? proposal.operations : [], new Map(items.map((item) => [item.id, item])));
  await recordPlanHistory({ tripProjectId: proposal.tripProjectId, userId: proposal.userId, proposalId: proposal.id, actor, operationClass: "expire", affectedItemReferences: summary.affectedItems, safeBeforeAfterSummary: boundBeforeAfterSummary(summary.beforeAfter) }, transaction);
  await recordAuditEvent({ actor, operation: "expire", targetType: "trip_change_proposal", targetId: proposal.id, afterSummary: JSON.stringify({ tripProjectId: proposal.tripProjectId, proposalId: proposal.id }) }, transaction);
  return { success: true, proposal: terminal(proposal, "expired", now, summary) };
}

async function loadActor(transaction: TripPlanCommandTransaction, userId: string) { const [user] = await transaction.select({ id: users.id, email: users.email }).from(users).where(eq(users.id, userId)).limit(1); return user?.email ? { userId: user.id, email: user.email } : null; }
async function lockProposal(transaction: TripPlanCommandTransaction, userId: string, input: ProposalCommandInput) { const [proposal] = await transaction.select({ id: tripChangeProposals.id, userId: tripChangeProposals.userId, status: tripChangeProposals.status, rationale: tripChangeProposals.rationale, operations: tripChangeProposals.operations, alternatives: tripChangeProposals.alternatives, expiresAt: tripChangeProposals.expiresAt, createdAt: tripChangeProposals.createdAt, terminalTimestamp: tripChangeProposals.terminalTimestamp, expectedAggregateVersion: tripChangeProposals.expectedAggregateVersion, expectedItemVersions: tripChangeProposals.expectedItemVersions, orderingPreconditions: tripChangeProposals.orderingPreconditions }).from(tripChangeProposals).where(and(eq(tripChangeProposals.id, input.proposalId), eq(tripChangeProposals.tripProjectId, input.tripProjectId), eq(tripChangeProposals.userId, userId), ...(input.requiredSourceAssistantMessageId ? [eq(tripChangeProposals.sourceAssistantMessageId, input.requiredSourceAssistantMessageId)] : []), ...(input.annotationBinding ? [eq(tripChangeProposals.sourceAssistantMessageId, input.annotationBinding.assistantMessageId)] : []))).limit(1).for("update"); return proposal; }
async function hasCurrentAnnotationActionBinding(transaction: TripPlanCommandTransaction, userId: string, tripProjectId: string, binding: AnnotationActionBinding) { if (!(binding.annotationId === "trip-change-proposal-apply" && binding.command === "trip_change_proposal.apply" || binding.annotationId === "trip-change-proposal-dismiss" && binding.command === "trip_change_proposal.dismiss")) return false; const provenance = await transaction.select({ id: assistantResponseProvenance.id, sourceCategory: assistantResponseProvenance.sourceCategory, rank: assistantResponseProvenance.rank, retrievalScore: assistantResponseProvenance.retrievalScore, sourceType: assistantResponseProvenance.sourceType, verificationStatus: assistantResponseProvenance.verificationStatus, availability: assistantResponseProvenance.availability, usedInPrompt: assistantResponseProvenance.usedInPrompt, citedInAnswer: assistantResponseProvenance.citedInAnswer, sourceSnapshot: assistantResponseProvenance.sourceSnapshot }).from(assistantResponseProvenance).where(and(eq(assistantResponseProvenance.assistantMessageId, binding.assistantMessageId), eq(assistantResponseProvenance.userId, userId), eq(assistantResponseProvenance.conversationId, binding.conversationId))).for("update"); const [message] = await transaction.select({ content: messages.content, answerAnnotations: messages.answerAnnotations }).from(messages).innerJoin(conversations, eq(conversations.id, messages.conversationId)).where(and(eq(messages.id, binding.assistantMessageId), eq(messages.conversationId, binding.conversationId), eq(messages.userId, userId), eq(messages.role, "assistant"), eq(conversations.userId, userId), eq(conversations.tripProjectId, tripProjectId))).limit(1).for("update"); return Boolean(message && sanitizeStoredPlanningAnnotations({ answerText: message.content, annotations: message.answerAnnotations, provenance: formatAssistantMessageProvenance(provenance) }).find((item) => item.id === binding.annotationId)?.detail.action?.command === binding.command); }
function terminal(row: Omit<TerminalProposalRow, "status" | "terminalTimestamp" | "affectedItems" | "beforeAfter"> & { status: TerminalProposalRow["status"]; terminalTimestamp?: Date | null }, status: TerminalProposalRow["status"], terminalTimestamp: Date | null, summary: { affectedItems: ProposalAffectedItem[]; beforeAfter: ProposalBeforeAfter[] }): TerminalProposalRow { return { id: row.id, userId: row.userId, status, rationale: row.rationale, operations: row.operations, alternatives: row.alternatives, expiresAt: row.expiresAt, createdAt: row.createdAt, terminalTimestamp, ...summary }; }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function validateOperationFences(operations: unknown[], items: Map<string, { id: string; version: number }>, expected: Record<string, number> | null, ordering: unknown) { for (const op of operations) { if (!isRecord(op)) return true; if (["update-item", "remove-item", "reorder-item", "change-item-state"].includes(op.kind as string)) { const id = typeof op.itemId === "string" ? op.itemId : ""; if (!id || items.get(id)?.version !== expected?.[id]) return true; } } if (ordering != null) { if (!isRecord(ordering) || Object.keys(ordering).some((key) => !recognizedOrderingPreconditionKeys.has(key))) return true; const versions = ordering.expectedChangedItemVersions; if (versions != null && (!isRecord(versions) || Object.entries(versions).some(([id, version]) => !Number.isInteger(version) || items.get(id)?.version !== version))) return true; } return false; }
function detectCrossOperationBackupCycle(operations: unknown[], items: Array<{ id: string; kind: string; backupTargetItemId: string | null }>, tripProjectId: string) { const changes = operations.filter((op): op is Record<string, unknown> => isRecord(op) && op.kind === "change-item-state" && typeof op.itemId === "string"); if (changes.length < 2) return false; const references = new Map<string, PlanItemReference>(items.map((item) => [item.id, { ...item, tripProjectId }])); for (const op of changes) { const item = references.get(op.itemId as string); if (item) references.set(item.id, { ...item, backupTargetItemId: typeof op.backupTargetItemId === "string" ? op.backupTargetItemId : null }); } return changes.some((op) => Boolean(validatePlanReferencesRules(tripProjectId, { kind: references.get(op.itemId as string)?.kind ?? "leg", backupTargetItemId: typeof op.backupTargetItemId === "string" ? op.backupTargetItemId : null }, [...references.values()], op.itemId as string))); }
async function executeOperation(transaction: TripPlanCommandTransaction, actor: { userId: string; email: string }, tripProjectId: string, aggregateVersion: number, operation: unknown, items: Map<string, typeof tripPlanItems.$inferSelect>, constraintsVersion: number | null, expectedVersions: Record<string, number> | null): Promise<{ success: true; aggregateVersion: number } | { success: false; reason: "refresh_required" | "not_found" | "expired" }> {
  if (!isRecord(operation)) return { success: false, reason: "refresh_required" };
  const fail = (reason: "unauthenticated" | "not_found" | "refresh_required" | "invalid") => ({ success: false as const, reason: reason === "not_found" ? "not_found" as const : "refresh_required" as const });
  if (operation.kind === "create-item" && isRecord(operation.item)) {
    const item = itemInput(operation.item, operation.parentItemId, operation.ordinal); if (!item) return { success: false, reason: "refresh_required" };
    const result = await createTripPlanItemInTransaction(transaction, actor, tripProjectId, aggregateVersion, normalizePlanItem(item)); if (!result.success) return fail(result.reason);
    if (result.itemId) items.set(result.itemId, { id: result.itemId, tripProjectId, userId: actor.userId, kind: item.kind, anchorRole: item.anchorRole ?? null, type: item.type ?? null, state: item.state, label: item.label, notes: item.notes ?? null, plannedAt: item.plannedAt ?? null, ordinal: item.ordinal, parentItemId: item.parentItemId ?? null, backupTargetItemId: item.backupTargetItemId ?? null, transportOriginLabel: item.transportOriginLabel ?? null, transportDestinationLabel: item.transportDestinationLabel ?? null, accommodationPlaceAreaLabel: item.accommodationPlaceAreaLabel ?? null, version: 1, createdAt: new Date(), updatedAt: new Date() });
    return { success: true, aggregateVersion: result.aggregateVersion };
  }
  const itemId = typeof operation.itemId === "string" ? operation.itemId : null; const current = itemId ? items.get(itemId) : null;
  if (!itemId || !current) return { success: false, reason: "refresh_required" };
  const expected = expectedVersions?.[itemId]; if (expected === undefined) return { success: false, reason: "refresh_required" };
  if (operation.kind === "update-item" && isRecord(operation.changes)) {
    const input = mergeItem(current, operation.changes); if (!input) return { success: false, reason: "refresh_required" }; const values = normalizePlanItem(input);
    const result = await updateTripPlanItemInTransaction(transaction, actor, tripProjectId, aggregateVersion, itemId, expected, values); if (!result.success) return fail(result.reason);
    items.set(itemId, { ...current, ...values, version: expected + 1 }); if (expectedVersions) expectedVersions[itemId] = expected + 1; return { success: true, aggregateVersion: result.aggregateVersion };
  }
  if (operation.kind === "remove-item") { const result = await deleteTripPlanItemInTransaction(transaction, actor, tripProjectId, aggregateVersion, itemId, expected); if (!result.success) return fail(result.reason); items.delete(itemId); if (expectedVersions) delete expectedVersions[itemId]; return { success: true, aggregateVersion: result.aggregateVersion }; }
  if (operation.kind === "change-item-state") { const backup = optionalId(operation.backupTargetItemId); const state = typeof operation.state === "string" && validStates.includes(operation.state as TripPlanItemState) ? operation.state as TripPlanItemState : null; if (backup === undefined || !state) return { success: false, reason: "refresh_required" }; const result = await changeInternalTripPlanItemStateInTransaction(transaction, actor, tripProjectId, aggregateVersion, itemId, expected, state, backup); if (!result.success) return fail(result.reason); items.set(itemId, { ...current, state, backupTargetItemId: backup, version: expected + 1 }); if (expectedVersions) expectedVersions[itemId] = expected + 1; return { success: true, aggregateVersion: result.aggregateVersion }; }
  if (operation.kind === "reorder-item") { const parentItemId = optionalId(operation.parentItemId); const ordinal = typeof operation.ordinal === "number" && Number.isInteger(operation.ordinal) && operation.ordinal >= 0 ? operation.ordinal : null; if (parentItemId === undefined || ordinal === null) return { success: false, reason: "refresh_required" }; const versions = reorderVersions(items, itemId, parentItemId); const result = await reorderTripPlanItemInTransaction(transaction, actor, tripProjectId, aggregateVersion, { itemId, expectedItemVersion: expected, parentItemId, ordinal, expectedChangedItemVersions: versions }); if (!result.success) return fail(result.reason); for (const id of Object.keys(versions)) { const item = items.get(id); if (item) { items.set(id, { ...item, ...(id === itemId ? { parentItemId, ordinal } : {}), version: item.version + 1 }); if (expectedVersions) expectedVersions[id] = item.version + 1; } } return { success: true, aggregateVersion: result.aggregateVersion }; }
  if (operation.kind === "upsert-constraints" && isRecord(operation.constraints)) { const expectedConstraint: number | null | -1 = operation.expectedConstraintsVersion === null || operation.expectedConstraintsVersion === undefined ? null : typeof operation.expectedConstraintsVersion === "number" && Number.isInteger(operation.expectedConstraintsVersion) ? operation.expectedConstraintsVersion : -1; if (expectedConstraint === -1) return { success: false, reason: "refresh_required" }; let values: ReturnType<typeof normalizeConstraints>; try { values = normalizeConstraints(operation.constraints); } catch { return { success: false, reason: "refresh_required" }; } const result = await upsertInternalTripProjectConstraintsInTransaction(transaction, actor, tripProjectId, aggregateVersion, expectedConstraint, values); return result.success ? { success: true, aggregateVersion: result.aggregateVersion } : fail(result.reason); }
  return { success: false, reason: "refresh_required" };
}
function optionalId(value: unknown): string | null | undefined { if (value === null || value === undefined) return null; return typeof value === "string" ? value.trim() || null : undefined; }
function itemInput(raw: Record<string, unknown>, parent: unknown, ordinal: unknown): InternalPlanItemInput | null { const parentItemId = optionalId(parent); const backupTargetItemId = optionalId(raw.backupTargetItemId); const plannedAt = raw.plannedAt === null || raw.plannedAt === undefined || raw.plannedAt === "" ? null : typeof raw.plannedAt === "string" && !Number.isNaN(Date.parse(raw.plannedAt)) ? new Date(raw.plannedAt) : undefined; if (parentItemId === undefined || backupTargetItemId === undefined || plannedAt === undefined || typeof ordinal !== "number" || !Number.isInteger(ordinal) || ordinal < 0 || typeof raw.kind !== "string" || typeof raw.state !== "string" || typeof raw.label !== "string") return null; return { kind: raw.kind as TripPlanItemKind, anchorRole: raw.anchorRole as TripPlanAnchorRole | null, type: raw.type as TripPlanItemType | null, state: raw.state as TripPlanItemState, label: raw.label, notes: typeof raw.notes === "string" ? raw.notes : null, plannedAt, ordinal, parentItemId, backupTargetItemId, transportOriginLabel: typeof raw.transportOriginLabel === "string" ? raw.transportOriginLabel : null, transportDestinationLabel: typeof raw.transportDestinationLabel === "string" ? raw.transportDestinationLabel : null, accommodationPlaceAreaLabel: typeof raw.accommodationPlaceAreaLabel === "string" ? raw.accommodationPlaceAreaLabel : null }; }
function mergeItem(current: typeof tripPlanItems.$inferSelect, changes: Record<string, unknown>): InternalPlanItemInput | null { const input = itemInput({ ...current, ...changes, plannedAt: changes.plannedAt === undefined ? current.plannedAt?.toISOString() ?? null : changes.plannedAt }, current.parentItemId, current.ordinal); return input; }
function reorderVersions(items: Map<string, typeof tripPlanItems.$inferSelect>, itemId: string, parentItemId: string | null) { const item = items.get(itemId); if (!item) return {}; const rows = [...items.values()]; const oldScope = rows.filter((row) => row.parentItemId === item.parentItemId && row.id !== itemId); const newScope = item.parentItemId === parentItemId ? oldScope : rows.filter((row) => row.parentItemId === parentItemId); return Object.fromEntries(new Set([...oldScope, ...newScope, item]).values().map((row) => [row.id, row.version])); }
async function loadPlanItems(transaction: TripPlanCommandTransaction, tripProjectId: string, userId: string) { return transaction.select().from(tripPlanItems).where(and(eq(tripPlanItems.tripProjectId, tripProjectId), eq(tripPlanItems.userId, userId))); }
function proposalSummary(operations: unknown[], items: Map<string, typeof tripPlanItems.$inferSelect>): { affectedItems: ProposalAffectedItem[]; beforeAfter: ProposalBeforeAfter[] } { const affectedItems: ProposalAffectedItem[] = []; const beforeAfter: ProposalBeforeAfter[] = []; for (const op of operations) { if (!isRecord(op)) continue; const item = typeof op.itemId === "string" ? items.get(op.itemId) : undefined; if (op.kind === "create-item" && isRecord(op.item) && typeof op.item.label === "string" && typeof op.item.kind === "string") { affectedItems.push({ itemId: "(mới)", kind: op.item.kind as TripPlanItemKind, label: op.item.label.slice(0, 160), change: "create" }); beforeAfter.push({ operation: "Tạo mục mới", before: null, after: op.item.label.slice(0, 160) }); } else if (op.kind === "upsert-constraints") { affectedItems.push({ itemId: "constraints", kind: "activity", label: "Ràng buộc", change: "upsert-constraints" }); beforeAfter.push({ operation: "Cập nhật ràng buộc", before: null, after: null }); } else if (item && typeof op.kind === "string") { const change: ProposalAffectedItem["change"] = op.kind === "update-item" ? "update" : op.kind === "remove-item" ? "remove" : op.kind === "reorder-item" ? "reorder" : "change-state"; affectedItems.push({ itemId: item.id, kind: item.kind, label: item.label, change }); if (op.kind === "remove-item") beforeAfter.push({ operation: "Xoá mục", before: item.label, after: null }); else if (op.kind === "reorder-item") beforeAfter.push({ operation: `Sắp xếp lại · ${item.label}`, before: `vị trí ${item.ordinal}`, after: typeof op.ordinal === "number" ? `vị trí ${op.ordinal}` : null }); else if (op.kind === "change-item-state") beforeAfter.push({ operation: `Đổi trạng thái · ${item.label}`, before: item.state, after: typeof op.state === "string" ? op.state : null }); else if (op.kind === "update-item" && isRecord(op.changes)) for (const [field, value] of Object.entries(op.changes)) beforeAfter.push({ operation: `Cập nhật ${field} · ${item.label}`, before: typeof item[field as keyof typeof item] === "string" ? item[field as keyof typeof item] as string : null, after: typeof value === "string" ? value : null }); } } return { affectedItems: affectedItems.slice(0, 20), beforeAfter: beforeAfter.slice(0, 20) }; }
function boundBeforeAfterSummary(entries: Array<{ operation: string; before: string | null; after: string | null }>) { for (let count = entries.length; count > 0; count--) { const payload = { entries: entries.slice(0, count) }; if (Buffer.byteLength(JSON.stringify(payload), "utf8") <= maxSafeSummaryBytes) return payload; } return { entries: [] }; }
