import { BadRequestException, Body, Controller, Get, HttpCode, HttpStatus, Inject, Param, Post, Put, Query, Req, ServiceUnavailableException } from "@nestjs/common";
import { parseAdminKnowledgeApprovedList, parseAdminKnowledgeApprovedQuery, parseAdminKnowledgeDraft, parseAdminKnowledgeDraftApprove, parseAdminKnowledgeDraftBatchApprove, parseAdminKnowledgeDraftBatchResult, parseAdminKnowledgeDraftList, parseAdminKnowledgeDraftResult, parseAdminKnowledgeDraftUpdate, parseAdminKnowledgeRecommendationDetail, parseAdminKnowledgeRecommendationList, parseAdminKnowledgeRecommendationListQuery, parseAdminKnowledgeRecommendationResolve, parseAdminKnowledgeRecommendationResult, type RequestPrincipal } from "@xuyenviet/contracts";
import { type AdminKnowledgeReviewPort, KnowledgeDraftReviewPolicyError } from "@xuyenviet/domain";
import { AllowsAdminBrowserSession, RequiresAdminCapability } from "../auth/admin-capability.decorator";
export const ADMIN_KNOWLEDGE_REVIEW_PORT = Symbol("ADMIN_KNOWLEDGE_REVIEW_PORT");
@Controller("v1/admin/knowledge") @RequiresAdminCapability("admin.knowledge.write") @AllowsAdminBrowserSession()
export class AdminKnowledgeReviewController {
  constructor(@Inject(ADMIN_KNOWLEDGE_REVIEW_PORT) private readonly review: AdminKnowledgeReviewPort) {}
  @Get("drafts") async drafts() { return checked(await this.review.listDrafts(), parseAdminKnowledgeDraftList); }
  @Get("drafts/:id") async draft(@Param("id") id: string) { return found(await this.review.getDraft(id), parseAdminKnowledgeDraft); }
  @Put("drafts/:id") async update(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminKnowledgeDraftUpdate(body); const principal = request.principal; if (!input || !principal) throw invalid(); return mutation(() => this.review.updateDraft(id, input, principal), parseAdminKnowledgeDraftResult); }
  @Post("drafts/:id/reject") @HttpCode(HttpStatus.OK) async reject(@Param("id") id: string, @Req() request: { principal?: RequestPrincipal }) { const principal = request.principal; if (!principal) throw invalid(); return mutation(() => this.review.rejectDraft(id, principal), parseAdminKnowledgeDraftResult); }
  @Post("drafts/:id/approve") @HttpCode(HttpStatus.OK) async approve(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminKnowledgeDraftApprove(body); const principal = request.principal; if (!input || !principal) throw invalid(); return mutation(() => this.review.approveDraft(id, principal, input.expectedUpdatedAt), parseAdminKnowledgeDraftResult); }
  @Post("drafts/approve") @HttpCode(HttpStatus.OK) async approveBatch(@Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminKnowledgeDraftBatchApprove(body); const principal = request.principal; if (!input || !principal) throw invalid(); return mutation(() => this.review.approveDraftBatch(input.draftIds, principal), parseAdminKnowledgeDraftBatchResult); }
  @Get("approved") async approved(@Query() query: Record<string, unknown>) { const input = parseAdminKnowledgeApprovedQuery(query); if (!input) throw invalid(); return checked(await this.review.listApproved(input.q), parseAdminKnowledgeApprovedList); }
  @Get("approved/:id") async approvedDetail(@Param("id") id: string) { return found(await this.review.getApproved(id), parseAdminKnowledgeApprovedListItem); }
  @Get("recommendations") async recommendations(@Query() query: Record<string, unknown>) { const input = parseAdminKnowledgeRecommendationListQuery(query); if (!input) throw invalid(); return checked(await this.review.listRecommendations(input), parseAdminKnowledgeRecommendationList); }
  @Get("recommendations/:id") async recommendation(@Param("id") id: string) { return found(await this.review.getRecommendation(id), parseAdminKnowledgeRecommendationDetail); }
  @Post("recommendations/:id/resolve") @HttpCode(HttpStatus.OK) async resolve(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminKnowledgeRecommendationResolve(body); const principal = request.principal; if (!input || !principal) throw invalid(); return mutation(() => this.review.resolveRecommendation(id, input, principal), parseAdminKnowledgeRecommendationResult); }
}
function parseAdminKnowledgeApprovedListItem(value: unknown) { const parsed = parseAdminKnowledgeApprovedList({ candidateCount: 1, items: [value] }); return parsed ? parsed.items[0] ?? null : null; }
function checked<T>(value: unknown, parser: (value: unknown) => T | null): T { const parsed = parser(value); if (!parsed) throw unavailable(); return parsed; }
function found<T>(value: unknown, parser: (value: unknown) => T | null): T { if (value === null) throw invalid(); return checked(value, parser); }
async function mutation<T>(run: () => Promise<unknown>, parser: (value: unknown) => T | null) { try { return checked(await run(), parser); } catch (error) { if (error instanceof KnowledgeDraftReviewPolicyError) throw invalid(); throw unavailable(); } }
function invalid() { return new BadRequestException({ code: "validation_error" }); } function unavailable() { return new ServiceUnavailableException({ code: "internal_error" }); }
