import { BadRequestException, Body, Controller, Get, HttpCode, HttpStatus, Inject, NotFoundException, Param, Post, Query, Req, ServiceUnavailableException } from "@nestjs/common";
import { parseAdminYoutubeDiscoveryAcceptCommand, parseAdminYoutubeDiscoveryAcceptReviewResult, parseAdminYoutubeDiscoveryActionRequiredCursor, parseAdminYoutubeDiscoveryActionRequiredQueue, parseAdminYoutubeDiscoveryCommand, parseAdminYoutubeDiscoveryDeferCommand, parseAdminYoutubeDiscoveryDeferReviewResult, parseAdminYoutubeDiscoveryHealthIncidentCursor, parseAdminYoutubeDiscoveryHealthIncidentDetail, parseAdminYoutubeDiscoveryHealthOverview, parseAdminYoutubeDiscoveryMissionCandidateCursor, parseAdminYoutubeDiscoveryMissionCandidatePage, parseAdminYoutubeDiscoveryMissionCoverageCursor, parseAdminYoutubeDiscoveryMissionCoveragePage, parseAdminYoutubeDiscoveryMissionDetail, parseAdminYoutubeDiscoveryMissionFunnel, parseAdminYoutubeDiscoveryMissionQueryCursor, parseAdminYoutubeDiscoveryMissionQueryPage, parseAdminYoutubeDiscoveryQuery, parseAdminYoutubeDiscoveryQueryList, parseAdminYoutubeDiscoveryReviewCursor, parseAdminYoutubeDiscoveryReviewDetail, parseAdminYoutubeDiscoveryReviewQueue, parseAdminYoutubeDiscoverySkipCommand, parseAdminYoutubeDiscoverySkipReviewResult, type RequestPrincipal } from "@xuyenviet/contracts";
import { YoutubeDiscoveryActionRequiredCursorValidationError, YoutubeDiscoveryHealthCursorValidationError, YoutubeDiscoveryMissionCursorValidationError, YoutubeDiscoveryReviewCursorValidationError, type AdminYoutubeDiscoveryPort } from "@xuyenviet/domain";
import { AllowsAdminBrowserSession, RequiresAdminCapability } from "../auth/admin-capability.decorator";

export const ADMIN_YOUTUBE_DISCOVERY_PORT = Symbol("ADMIN_YOUTUBE_DISCOVERY_PORT");
@Controller("v1/admin/knowledge/youtube-discovery") @RequiresAdminCapability("admin.knowledge.write") @AllowsAdminBrowserSession()
export class AdminYoutubeDiscoveryController {
  constructor(@Inject(ADMIN_YOUTUBE_DISCOVERY_PORT) private readonly port: AdminYoutubeDiscoveryPort) {}
  @Get() async list() { try { const value = await this.port.list(); if (!parseAdminYoutubeDiscoveryQueryList(value)) throw unavailable(); return value; } catch (error) { if (error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Get("review") async review(@Query() query: Record<string, unknown>, @Req() request: { principal?: RequestPrincipal }) { if (Object.keys(query).some((key) => key !== "cursor") || ("cursor" in query && typeof query.cursor !== "string") || !request.principal) throw invalid(); const cursor = query.cursor as string | undefined; const parsed = cursor === undefined ? null : parseAdminYoutubeDiscoveryReviewCursor(cursor); if (cursor !== undefined && !parsed) throw invalid(); try { const value = await this.port.listReview(request.principal, parsed); if (!parseAdminYoutubeDiscoveryReviewQueue(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryReviewCursorValidationError) throw invalid(); if (error instanceof BadRequestException || error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Get("action-required") async actionRequired(@Query() query: Record<string, unknown>, @Req() request: { principal?: RequestPrincipal }) { if (Object.keys(query).some((key) => key !== "cursor") || ("cursor" in query && typeof query.cursor !== "string") || !request.principal) throw invalid(); const cursor = query.cursor as string | undefined; const parsed = cursor === undefined ? null : parseAdminYoutubeDiscoveryActionRequiredCursor(cursor); if (cursor !== undefined && !parsed) throw invalid(); try { const value = await this.port.listActionRequired(request.principal, parsed); if (!parseAdminYoutubeDiscoveryActionRequiredQueue(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryActionRequiredCursorValidationError) throw invalid(); throw unavailable(); } }
  @Get("health") async health(@Query() query: Record<string, unknown>) { if (Object.keys(query).length) throw invalid(); try { const value = await this.port.healthOverview(); if (!parseAdminYoutubeDiscoveryHealthOverview(value)) throw unavailable(); return value; } catch { throw unavailable(); } }
  @Get("health/:groupId") async healthIncident(@Param("groupId") groupId: string, @Query() query: Record<string, unknown>) { if (!/^[a-f0-9]{8}-[a-f0-9]{4}-[1-5][a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}:(provider_rate_limited|triage_schema_invalid|execution_terminal)$/.test(groupId)) throw notFound(); const cursor = singleCursor(query, parseAdminYoutubeDiscoveryHealthIncidentCursor); if (cursor && cursor.groupId !== groupId) throw invalid(); try { const value = await this.port.getHealthIncident(groupId, cursor); if (!value) throw notFound(); if (!parseAdminYoutubeDiscoveryHealthIncidentDetail(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryHealthCursorValidationError || error instanceof BadRequestException) throw invalid(); if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Get("mission/coverage") async missionCoverage(@Query() query: Record<string, unknown>) { const cursor = singleCursor(query, parseAdminYoutubeDiscoveryMissionCoverageCursor); try { const value = await this.port.listMissionCoverage(cursor); if (!parseAdminYoutubeDiscoveryMissionCoveragePage(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryMissionCursorValidationError || error instanceof BadRequestException) throw invalid(); throw unavailable(); } }
  @Get("mission/queries") async missionQueries(@Query() query: Record<string, unknown>) { const cursor = singleCursor(query, parseAdminYoutubeDiscoveryMissionQueryCursor); try { const value = await this.port.listMissionQueries(cursor); if (!parseAdminYoutubeDiscoveryMissionQueryPage(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryMissionCursorValidationError || error instanceof BadRequestException) throw invalid(); throw unavailable(); } }
  @Get("mission/candidates") async missionCandidates(@Query() query: Record<string, unknown>) { const cursor = singleCursor(query, parseAdminYoutubeDiscoveryMissionCandidateCursor); try { const value = await this.port.listMissionCandidates(cursor); if (!parseAdminYoutubeDiscoveryMissionCandidatePage(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryMissionCursorValidationError || error instanceof BadRequestException) throw invalid(); throw unavailable(); } }
  @Get("mission/funnel") async missionFunnel(@Query() query: Record<string, unknown>) { if (Object.keys(query).length) throw invalid(); try { const value = await this.port.missionFunnel(); if (!parseAdminYoutubeDiscoveryMissionFunnel(value)) throw unavailable(); return value; } catch { throw unavailable(); } }
  @Get("mission/:actionId") async missionDetail(@Param("actionId") actionId: string, @Query() query: Record<string, unknown>) { if (!/^mission-[a-f0-9]{32}$/.test(actionId)) throw invalid(); const cursor = singleCursor(query, parseAdminYoutubeDiscoveryMissionCandidateCursor); if (cursor && cursor.actionId !== actionId) throw invalid(); try { const value = await this.port.getMissionDetail(actionId, cursor); if (!value) throw notFound(); if (!parseAdminYoutubeDiscoveryMissionDetail(value)) throw unavailable(); return value; } catch (error) { if (error instanceof YoutubeDiscoveryMissionCursorValidationError || error instanceof BadRequestException) throw invalid(); if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Get("review/:recommendationId") async detail(@Param("recommendationId") recommendationId: string, @Req() request: { principal?: RequestPrincipal }) { if (!validId(recommendationId) || !request.principal) throw invalid(); let value: Awaited<ReturnType<AdminYoutubeDiscoveryPort["getReview"]>>; try { value = await this.port.getReview(request.principal, recommendationId); } catch { throw unavailable(); } if (!value) throw notFound(); if (!parseAdminYoutubeDiscoveryReviewDetail(value)) throw unavailable(); return value; }
  @Post("review/:recommendationId/accept") async accept(@Param("recommendationId") recommendationId: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { if (!validId(recommendationId) || !parseAdminYoutubeDiscoveryAcceptCommand(body) || !request.principal) throw invalid(); try { const result = await this.port.acceptReview(request.principal, recommendationId); if (!result) throw notFound(); if (!parseAdminYoutubeDiscoveryAcceptReviewResult(result)) throw unavailable(); return result; } catch (error) { if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Post("review/:recommendationId/defer") async defer(@Param("recommendationId") recommendationId: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { if (!validId(recommendationId) || !parseAdminYoutubeDiscoveryDeferCommand(body) || !request.principal) throw invalid(); try { const result = await this.port.deferReview(request.principal, recommendationId); if (!result) throw notFound(); if (!parseAdminYoutubeDiscoveryDeferReviewResult(result)) throw unavailable(); return result; } catch (error) { if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Post("review/:recommendationId/skip") async skip(@Param("recommendationId") recommendationId: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { if (!validId(recommendationId) || !parseAdminYoutubeDiscoverySkipCommand(body) || !request.principal) throw invalid(); try { const result = await this.port.skipReview(request.principal, recommendationId); if (!result) throw notFound(); if (!parseAdminYoutubeDiscoverySkipReviewResult(result)) throw unavailable(); return result; } catch (error) { if (error instanceof NotFoundException || error instanceof ServiceUnavailableException) throw error; throw unavailable(); } }
  @Post() @HttpCode(HttpStatus.CREATED) async create(@Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminYoutubeDiscoveryCommand(body, "create"); if (!input || !request.principal) throw invalid(); return call(() => this.port.create(request.principal!, input as { queryText: string; priority: number; cadenceMinutes: number })); }
  @Post(":id/text") async edit(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminYoutubeDiscoveryCommand(body, "edit"); if (!input || !request.principal || !validId(id)) throw invalid(); return call(() => this.port.edit(request.principal!, id, input.queryText!)); }
  @Post(":id/priority") async priority(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { const input = parseAdminYoutubeDiscoveryCommand(body, "priority"); if (!input || !request.principal || !validId(id)) throw invalid(); return call(() => this.port.reprioritize(request.principal!, id, input.priority!)); }
  @Post(":id/pause") async pause(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { if (!parseAdminYoutubeDiscoveryCommand(body, "empty") || !request.principal || !validId(id)) throw invalid(); return call(() => this.port.pause(request.principal!, id)); }
  @Post(":id/resume") async resume(@Param("id") id: string, @Body() body: unknown, @Req() request: { principal?: RequestPrincipal }) { if (!parseAdminYoutubeDiscoveryCommand(body, "empty") || !request.principal || !validId(id)) throw invalid(); return call(() => this.port.resume(request.principal!, id)); }
}
async function call(operation: () => Promise<unknown>) { try { const result = await operation(); if (!parseAdminYoutubeDiscoveryQuery(result)) throw invalid(); return result; } catch (error) { if (error instanceof BadRequestException) throw error; throw unavailable(); } }
function invalid() { return new BadRequestException({ code: "validation_error" }); }
function unavailable() { return new ServiceUnavailableException({ code: "internal_error" }); }
function notFound() { return new NotFoundException({ code: "not_found" }); }
function validId(value: string) { return value.trim() === value && value.length > 0 && value.length <= 128; }
function singleCursor<T>(query: Record<string, unknown>, parse: (value: unknown) => T | null): T | null { if (Object.keys(query).some((key) => key !== "cursor") || ("cursor" in query && typeof query.cursor !== "string")) throw invalid(); if (!("cursor" in query)) return null; const cursor = parse(query.cursor); if (!cursor) throw invalid(); return cursor; }
